---
sidebar: sidebar
permalink: integrations/dashboard-access.html
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, Keystone subscriptions
summary: As a NetApp Keystone STaaS subscriber, you can get access the Keystone dashboard through NetApp BlueXP or Digital Advisor
---

= Get started with Keystone dashboard
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can access the Keystone dashboard through NetApp BlueXP or Digital Advisor after subscribing to NetApp Keystone services. <might change after completing the dashboard overview part>

NOTE: You can also access the Keystone dashboard from BlueXP digital advisor. To learn more, refer to link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-cm.html[Learn about Keystone and BlueXP digital advisor]. 

[role="tabbed-block"]
====

.BlueXP
--
To log in to BlueXP, you can use your NetApp Support Site credentials or you can sign up for a NetApp cloud login using your email and a password. Learn more about link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html[logging in to BlueXP^].

.Steps
. Open a web browser and go to the link:https://console.bluexp.netapp.com/[BlueXP console^].
. The NetApp BlueXP login page appears.
. Log in to BlueXP.
. From the BlueXP left navigation, select *Storage > Keystone*.
+
The Keystone dashboard appears.
+
<image requires to show the landing page-Deb>.
. If you are an existing Keystone user,
+
.. Click *Discover your subscriptions* to view the details about your subscriptions in the Keystone dashboard. 
.. If subscriptions are not found, click *Add subscriptions manually*.
.. Provide the required values and click *Discover* to view all your subscriptions.
.. Select your subscriptions and click *Next*.
.. Review details and click *Submit request* to view the details about your subscriptions in the Keystone dashboard.
. If you are new to Keystone, click *Contact sales team*, provide the requested details, and click *Submit*.

--


.Digital Advisor
--

The Digital Advisor dashboard enables you to view the details of your Keystone subscriptions. To log in to Digital Advisor, you can use your NetApp Support Site credentials.

.Steps
. Open a web browser, and go to the link:https://activeiq.netapp.com/?source=onlinedocs[Digital Advisor^] login page.
. Provide your username and password and click *Sign In*.
+
You can view the details of your subscription and usage, and see a summary of capacity usage against your purchased Keystone services, on the *Keystone Subscriptions* widget in the Digital Advisor dashboard. To learn more about the *Keystone Subscriptions* widget, refer to link:../integrations/keystone-aiq.html[Keystone dashboard in Digital Advisor].
--
====

*Related information*

* link:../integrations/keystone-bluexp.html[Keystone dashboard in BlueXP]
* link:..//integrations/keystone-aiq.html[Keystone dashboard in Digital Advisor]
* link:../integrations/subscriptions-tab.html[View your subscription details]









