---
sidebar: sidebar
permalink: integrations/dashboard-overview.html
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard
summary: As a NetApp Keystone STaaS subscriber, you can get an overview of your subscriptions from  NetApp BlueXP or Digital Advisor.
---

= Learn about Keystone dashboard
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
##The Keystone dashboard enables you to view and efficiently manage your Keystone subscriptions with a comprehensive suite of features. The Keystone dashboard is now accessible through BlueXP, which is also available through Active IQ Digital Advisor (also known as Digital Advisor).Through the Keystone dashboard, you can achieve the following goals:##

* *Monitor subscription details*: View detailed information about your Keystone subscriptions, including assets across different subscriptions or specific subscription assets.
* *Track capacity usage and generate reports*: Keep track of current and historical capacity usage, and generate insightful reports to analyze subscription data and make informed decisions.
* *Track subscription timeline*: Stay informed about key dates and events by monitoring the timeline of your subscriptions.
* *Manage committed capacity*: Request changes to the committed capacity for your service levels to ensure your subscriptions align with your needs.
* *Analyze volumes and objects*: Access detailed insights into the volumes and objects of your subscriptions, including their capacity at both the volume and object levels.

== Access and availability
##You can access the Keystone dashboard through both BlueXP and Digital Advisor. While features are exclusive to each platform, BlueXP provides administrative functionality for Keystone, allowing you to manage Keystone subscriptions and request modifications to the committed capacity for your service levels.##

[NOTE]
====
* You must have Keystone admin privileges to create or cancel service requests, or modify subscriptions. To learn more, refer to link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-keystone-roles.html[Keystone access roles for BlueXP^].
* ##Digital Advisor is integrated with BlueXP, allowing you to manage your clusters and access all Digital Advisor features, including the Keystone dashboard, directly from the BlueXP user interface (UI). To learn more, refer to link:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-bluexp.html#integration-overview[Digital Advisor integration with BlueXP^] and link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-cm.html[Learn about Keystone and BlueXP digital advisor]. ##
====

The table indicates the availability of features from BlueXP and Digital Advisor:


|===

|Feature |BlueXP |Digital Advisor

a|link:../integrations/subscriptions-tab.html[View your subscription details]
|Yes
|Yes
a|link:../integrations/current-usage-tab.html[Monitor current and historical capacity usage]
|Yes
|Yes
a|link:../integrations/subscription-timeline.html[Track subscription timeline]
|Yes
|No
a|link:../integrations/assets-tab.html[View assets associated with a Keystone subscription]
|Yes
|Yes
|link:../integrations/assets.html[View assets across multiple Keystone subscriptions]
|Yes
|No
a|link:../integrations/modify-subscription.html[Modify your subscriptions] (only for Keystone administrators)
|Yes
|No
a|link:../integrations/administration-tab.html[View or cancel your service requests] 
|Yes
|No
a|link:../integrations/options.html#generate-reports-from-bluexp-or-digital-advisor[Generate reports]
|Yes
|Yes
a|link:../integrations/options.html#generate-consolidated-report-from-digital-advisor[Generate consolidated report and view alerts]
|No
|Yes
a|link:../integrations/volumes-objects-tab.html[View volumes and objects details]
|No
|Yes
a|link:../integrations/performance-tab.html[View performance metrics]
|No
|Yes

|===


*Related information*

* link:../integrations/dashboard-access.html[Get started with Keystone dashboard]
* link:../integrations/keystone-bluexp.html[Keystone dashboard in BlueXP]
* link:..//integrations/keystone-aiq.html[Keystone dashboard in Digital Advisor]