---
sidebar: sidebar
permalink: integrations/dashboard-overview.html
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console
summary: As a NetApp Keystone STaaS subscriber, you can get an overview of your subscriptions from  NetApp Console or Digital Advisor.
---

= Learn about the Keystone dashboard
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The Keystone dashboard is your go-to solution for efficiently monitoring, analyzing, and managing your Keystone subscriptions. Through the Keystone dashboard, you can achieve the following goals:

* *Monitor subscription details*: View detailed information about your Keystone subscriptions, including performance service levels, capacity usage, assets, and alerts. 
* *Track capacity usage and generate reports*: Keep track of current and historical capacity usage, and generate reports to analyze subscription data and make informed decisions.
* *View subscription timeline*: Stay informed about key dates and events by monitoring the timeline of your subscriptions.
//* *Manage subscriptions*: Request changes for your service levels to ensure your subscriptions align with your needs.
* *Manage subscriptions*: Submit requests to modify performance service levels or other subscription parameters as your needs change.
* *Analyze volumes and objects*: Gain detailed insights into the volumes and objects of your subscriptions, including their capacity at both the volume and object levels.

== Access the Keystone dashboard

You can access the Keystone dashboard through:

* *NetApp Console*: Access the dashboard from *Storage > Keystone > Overview* in the Console. To learn more, refer to link:../integrations/keystone-console.html[Keystone dashboard in NetApp Console^].
* *Active IQ Digital Advisor* (also known as Digital Advisor): Access the dashboard from *General > Keystone Subscriptions* in Digital Advisor. To learn more, refer to link:../integrations/keystone-aiq.html[Keystone dashboard in Digital Advisor^].

== About NetApp Console

Keystone is accessible through the NetApp Console.

The NetApp Console provides centralized management of NetApp storage and data services across on-premises and cloud environments at enterprise scale. The Console is required to access and use NetApp data services. As a management interface, it enables you to manage many storage resources from one interface. Console administrators can control access to storage and services for all systems within the enterprise.

You don’t need a license or subscription to start using the Console and you only incur charges when you need to deploy Console agents in your cloud to ensure connectivity to your storage systems or NetApp data services. However, some NetApp data services accessible from the Console are licensed or subscription-based.

Learn more about the link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html[NetApp Console^].

Note the following:

* While the Console and Digital Advisor offer some exclusive features, the Console provides administrative functionality for Keystone, allowing you to manage subscriptions and make necessary adjustments.
* You must be assigned to the *Keystone admin* role to modify subscriptions. To learn more, refer to link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles^].
* Digital Advisor is integrated with the Console, allowing you to access all Digital Advisor features, including the Keystone dashboard, directly from the Console. To learn more, refer to link:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console[Digital Advisor integration with NetApp Console^].

== Keystone features in NetApp Console and Digital Advisor

The following table shows the availability of features in the NetApp Console and Digital Advisor, helping you quickly identify the right platform for your needs:

|===

|*Feature* |*NetApp Console* |*Digital Advisor*

a|link:../integrations/subscriptions-tab.html[View your subscription details]
|Yes
|Yes
a|link:../integrations/current-usage-tab.html[Monitor current and historical capacity usage]
|Yes
|Yes
a|link:../integrations/subscription-timeline.html[Track subscription timeline]
|Yes
|No
a|link:../integrations/assets-tab.html[View assets associated with a Keystone subscription]
|Yes
|Yes
|link:../integrations/assets.html[View assets across multiple Keystone subscriptions]
|Yes
|No
a|link:../integrations/monitoring-alerts.html[View and manage alerts and monitors]
|Yes
|No
a|link:../integrations/modify-subscription.html[Modify your subscriptions] (only for Keystone administrators)
|Yes
|No
a|link:../integrations/options.html#generate-reports-from-netapp-console-or-digital-advisor[Generate reports]
|Yes
|Yes
a|link:../integrations/volumes-objects-tab.html[View volumes and objects details]
|Yes
|Yes
a|link:../integrations/performance-tab.html[View performance metrics]
|No
|Yes

|===


*Related information*

* link:../integrations/dashboard-access.html[Get started with the Keystone dashboard]
* link:../integrations/keystone-console.html[Keystone dashboard in NetApp Console]
* link:..//integrations/keystone-aiq.html[Keystone dashboard in Digital Advisor]


//The Keystone dashboard enables you to view and efficiently manage your Keystone subscriptions with a comprehensive suite of features. This dashboard is now accessible through BlueXP, which is also available through Active IQ Digital Advisor (also known as Digital Advisor). Through the Keystone dashboard, you can achieve the following goals: