---
sidebar: sidebar
permalink: integrations/keystone-aiq.html
keywords: Keystone, Digital Advisor, keystone-aiq, aiq
summary: Keystone and Digital Advisor
---

= Keystone and Digital Advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you have subscribed to NetApp Keystone STaaS services, you get an overview of your subscriptions on the *Keystone Subscriptions* widget of the Active IQ Digital Advisor (Digital Advisor) dashboard. You can see information about capacity usage and warnings or alerts that require immediate attention or action.

The information appears selectively depending on your subscriptions and the status of your usage. You can view this information:

* Capacity usage, such as:
** No usage.
** Consumption exceeding 80% of the committed capacity.
** Burst usage.
** Consumptions above the burst capacity.
* SLA details: Whether the subscriptions meet the sustainability goals defined in your SLA.
* Miscellaneous warnings are displayed if they are applicable for you.
** *Expiring soon*: In case your subscriptions expire within 90 days.
** *Critical Hardware Upgrades*: Any critical hardware upgrades are pending.
** *AQoS Warnings*: You have volumes without AQoS policies assigned.

[TIP]
Click the *Subscriptions* link to view the list of filtered subscriptions in the *All Subscriptions* tab.

For more information about Digital Advisor dashboard widget for Keystone, see https://docs.netapp.com/us-en/active-iq/view_keystone_capacity_utilization.html[Digital Advisor documentation^].

For more information about Keystone dashboard and reporting, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting].

