---
sidebar: sidebar
permalink: integrations/keystone-cm.html
keywords: Keystone-Cloud Manager
summary: Keystone and Cloud Manager
---

= Keystone and Cloud Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you purchase a cloud service on your Keystone subscription, you can access and manage those services through Cloud Manager.

As a Keystone customer, if you have Cloud Volumes ONTAP subscription, you can use Keystone services to charge your Cloud Volumes ONTAP usage and view your billing and consumption details through Cloud Manager.

For this, you should create one or more Cloud Manager accounts and link them with your Keystone account. While you purchase a cloud service through Keystone, you need to provide the details of your Cloud Manager accounts to your Keystone Success Manager. This enables proper metering and charging of your cloud service usage through your Keystone subscription.

For more information, see the following links in the Cloud Manager documents:
link:https://docs.netapp.com/us-en/occm/concept_licensing.html#keystone-flex-subscription[Keystone Subscription]
link:https://docs.netapp.com/us-en/occm/task_managing_licenses.html#manage-keystone-flex-subscriptions[Manage Keystone Subscriptions]
