---
sidebar: sidebar
permalink: integrations/keystone-cm.html
keywords: Keystone-BlueXP
summary: Keystone and BlueXP
---

= Keystone and BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you purchase a cloud service on your Keystone subscription, you can access and manage those services through BlueXP.

As a Keystone customer, if you have Cloud Volumes ONTAP subscription, you can use Keystone services to charge your Cloud Volumes ONTAP usage and view your billing and consumption details through BlueXP.

For this, you should create one or more BlueXP accounts and link them with your Keystone account. While you purchase a cloud service through Keystone, you need to provide the details of your BlueXP accounts to your Keystone Success Manager. This enables proper metering and charging of your cloud service usage through your Keystone subscription.

For more information, see the following links in the BlueXP documents:

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription[Keystone Subscription]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html[Manage Keystone Subscriptions]


