---
sidebar: sidebar
permalink: integrations/keystone-aiq.html
keywords: Keystone, Digital Advisor, keystone-aiq, aiq
summary: Keystone and Digital Advisor
---

= Keystone and Digital Advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you have subscribed to NetApp Keystone services, you can view your usage reports and graphs on the Digital Advisor dashboard. 

Digital Advisor enables you to view storage-as-a-service (STaaS) details and information on the NetApp infrastructure that you own. Digital Advisor provides a single dashboard with visibility into your subscriptions, service levels, and capacity usage with the ability to create detailed reports.

For more information about Digital Advisor dashboard widget for Keystone, see https://docs.netapp.com/us-en/active-iq/view_keystone_capacity_utilization.html[Digital Advisor documentation^].

For more information about Keystone dashboard and reporting, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting].

For more information about data flow, see link:../concepts/infra.html[Monitoring tools].

