---
sidebar: sidebar
permalink: integrations/keystone-cm.html
keywords: Keystone-BlueXP
summary: If you purchased a cloud service with your NetApp Keystone subscription, you can access and manage those services through BlueXP.
---

= Learn about Keystone and BlueXP digital advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp BlueXP is a single control plane to build, protect, and govern data across your on-premises and cloud environments. If you purchase a cloud service on your NetApp Keystone subscription, you can access and manage those services through BlueXP.

The BlueXP digital advisor dashboard provides you with a graphical view and drill-down capabilities to monitor your Keystone subscription usage and generate reports. For more information about Digital Advisor dashboard and Keystone, see link:../integrations/keystone-aiq.html[Keystone dashboard and reporting].

As a Keystone customer, if you have Cloud Volumes ONTAP subscription, you can use Keystone services to charge your Cloud Volumes ONTAP usage and view your billing and consumption details through BlueXP.

For this, you should create one or more BlueXP accounts and link them with your Keystone account. While you purchase a cloud service through Keystone, you need to provide the details of your BlueXP accounts to your Keystone Success Manager (KSM). This enables proper metering and charging of your cloud service usage through your Keystone subscription.

For more information about Keystone and BlueXP, see the following links in the BlueXP documents:

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription[Keystone Subscription^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html[Manage Keystone Subscriptions^]


