---
sidebar: sidebar
permalink: integrations/keystone-advisor.html
keywords: Keystone, Digital Advisor, keystone-aiq, digital advisor, keystone advisor
summary: Keystone Advisor
---

= Keystone Advisor
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone is a pay-as-you-grow subscription-based service model that delivers a seamless hybrid cloud experience for those preferring OPEX consumption models to upfront CAPEX or leasing. Keystone Advisor, embedded in Digital Advisor, calculates, and provides recommendations and price related details of different subscription plans of Keystone.

For more information about Digital Advisor, see https://docs.netapp.com/us-en/active-iq/task_view_keystone_capacity_utilization.html[Digital Advisor documentation].

.Steps
. From the *Subscription Cluster Advisor*, select a cluster to view the pricing details for the subscriptions.
. From *Subscription Options*, select the currency and the number of years.
. Click *Calculate Price*. Based on the selection, the price and the capacity details are updated for each subscription.
. Click *Consult* to navigate to Fusion for more information.



