---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Keystone docs
      url: "/index.html"
    - title: Release notes
      entries:
        - title: What's new in Keystone STaaS
          url: /release-notes/whats-new.html
        - title: Known limitations
          url: /release-notes/known-limitations.html
    - title: Welcome to Keystone
      url: /concepts/overview.html
    - title: Set up and configure Keystone
      entries:
        - title: What is Keystone Collector
          url: /installation/installation-overview.html
        - title: Prepare your system for installing Keystone Collector
          entries:
            - title: VMware vSphere requirements
              url: /installation/vapp-prereqs.html
            - title: Linux requirements
              url: /installation/linux-prereqs.html
            - title: ONTAP and StorageGRID requirements
              url: /installation/addl-req.html
        - title: Install Keystone Collector
          entries:
            - title: VMware vSphere deployment
              url: /installation/vapp-installation.html
            - title: Linux installation
              url: /installation/linux-installation.html
            - title: Automatic integrity validation
              url: /installation/validation.html
        - title: Configure Keystone Collector
          url: /installation/configuration.html
        - title: Monitor system health
          url: /installation/monitor-health.html
        - title: Upgrade Keystone Collector
          url: /installation/upgrade.html
        - title: Configure AutoSupport for Keystone
          url: /installation/asup-config.html
        - title: Data collected for billing
          url: /installation/data-collection.html
    - title: Learn about Keystone
      entries:    
        - title: Supported storage capacity
          url: /concepts/supported-storage-capacity.html
        - title: Metrics and definitions
          url: /concepts/metrics.html
        - title: Supported storage in Keystone
          url: /concepts/supported-storage-services.html
        - title: Service Levels in Keystone
          url: /concepts/service-levels.html
        - title: Add-on Services
          entries:
            - title: Data tiering
              url: /concepts/data-tiering.html
            - title: Advanced data protection
              url: /concepts/adp.html
            - title: U.S. Citizen Support (USCS)
              url: /concepts/uscs.html
            - title: Non-returnable, non-volatile components and SnapLock compliance
              url: /concepts/nrnvc.html
            - title: Keystone and Equinix
              url: /concepts/equinix.html
    - title: More about Service Levels
      entries:
        - title: Quality of Service
          url: /concepts/qos.html
        - title: Capacity requirements for Service Levels
          url: /concepts/capacity-requirements.html
        - title: Reallocation of expenses from on-premises to cloud service
          url: /concepts/reallocate-spends.html      
    - title: Billing
      entries:
        - title: Keystone pricing
          url: /concepts/pricing.html
        - title: Billing based on committed capacity
          url: /concepts/committed-capacity-billing.html
        - title: Metering based on consumed capacity
          url: /concepts/consumed-capacity-billing.html
        - title: Billing based on burst consumption
          url: /concepts/burst-consumption-billing.html
        - title: Billing based on miscellaneous volume types
          url: /concepts/misc-volume-billing.html
        - title: Billing schedules
          url: /concepts/billing-schedules.html
    - title: Partner and customer-operated environments
      url: /concepts/operational-models.html
    - title: Keystone infrastructure
      entries:
       -  title: Infrastructure details
          url: /concepts/infra.html
       -  title: Components
          url: /concepts/components.html
       -  title: Data flow
          url: /concepts/data-flow.html
    - title: Keystone STaaS SLA
      entries:
        - title: Availability SLA service levels
          url: /concepts/sla-availability.html
        - title: Performance SLA service levels
          url: /concepts/sla-performance.html                       
        - title: Sustainability SLA service levels
          url: /concepts/sla-sustainability.html         
    - title: NetApp Global Services Support Center
      url: /concepts/gssc.html
    - title: Do more with Keystone Services
      entries:
       -  title: Keystone and BlueXP
          url: /integrations/keystone-cm.html
       -  title: Keystone and Active IQ Digital Advisor
          url: /integrations/keystone-aiq.html
       - title: Active IQ Digital Advisor reporting for Keystone
         url: /integrations/aiq-keystone-details.html
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: What is NetApp Keystone?
          url: /concepts/overview.html
        - title: Installing Keystone Collector on VMware vSphere
          url: /installation/vapp-installation.html
        - title: Installing Keystone Collector on Linux
          url: /installation/linux-installation.html    
        - title: What are the units of measurement?
          url: /concepts/metrics.html
        - title: What is the supported base storage?
          url: /concepts/supported-storage-services.html
        - title: How can I see my consumption data?
          url: /integrations/keystone-aiq.html        
    - title: Supported services in Keystone
      links:
        - title: Keystone Service Levels
          url: /concepts/service-levels.html
        - title: Quality of Service (QoS)
          url: /concepts/qos.html
        - title: What is data tiering?
          url: /concepts/data-tiering.html
        - title: Is my Keystone data protected?
          url: /concepts/adp.html
        - title: How can I see my consumption per service level?
          url: /integrations/aiq-keystone-details.html 
    - title: Keystone pricing
      links:
      - title: Know about Keystone billing
        url: /concepts/pricing.html
      - title: My billing schedules
        url: /concepts/billing-schedules.html
      - title: Billing based on committed capacity
        url: /concepts/committed-capacity-billing.html
      - title: Metering based on consumed capacity
        url: /concepts/consumed-capacity-billing.html
      - title: What happens if I have consumed more than my committed capacity?
        url: /concepts/burst-consumption-billing.html
    - title: Do more with Keystone Services
      links:
        - title: Know your support team (Keystone GSSC)
          url: /concepts/gssc.html
        - title: Keystone and BlueXP
          url: /integrations/keystone-cm.html
        - title: Keystone and Active IQ Digital Advisor
          url: /integrations/keystone-aiq.html
        - title: US Citizen Support
          url: /concepts/uscs.html
    - title: Know more
      links:
        - title: Keystone Subscriptions version 1 (previously, Keystone Flex Subscriptions)
          url: https://docs.netapp.com/us-en/keystone/
        - title: Active IQ Digital Advisor
          url: https://docs.netapp.com/us-en/active-iq/index.html
        - title: BlueXP
          url: https://docs.netapp.com/us-en/cloud-manager-family/
        - title: Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/
