---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Keystone docs
      url: "/index.html"
    - title: Release notes
      entries:
        - title: What's new in Keystone STaaS
          url: /release-notes/whats-new.html
        - title: Fixed issues
          url: /release-notes/fixed-issues.html  
        - title: Known issues
          url: /release-notes/known-issues.html  
        - title: Known limitations
          url: /release-notes/known-limitations.html          
    - title: Welcome to Keystone
      url: /concepts/overview.html
    - title: Set up and configure Keystone
      entries:
        - title: What is Keystone Collector
          url: /installation/installation-overview.html
        - title: Prepare your system
          entries:
            - title: VMware vSphere requirements
              url: /installation/vapp-prereqs.html
            - title: Linux requirements
              url: /installation/linux-prereqs.html
            - title: ONTAP and StorageGRID requirements
              url: /installation/addl-req.html
        - title: Install Keystone Collector
          entries:
            - title: VMware vSphere deployment
              url: /installation/vapp-installation.html
            - title: Linux installation
              url: /installation/linux-installation.html
            - title: Automatic integrity validation
              url: /installation/validation.html
        - title: Configure Keystone Collector
          url: /installation/configuration.html
        - title: Monitor system health
          url: /installation/monitor-health.html
        - title: Upgrade Keystone Collector
          url: /installation/upgrade.html
        - title: Configure AutoSupport for Keystone
          url: /installation/asup-config.html
        - title: Keystone Collector security
          url: /installation/security.html
        - title: Data collected for billing
          url: /installation/data-collection.html
    - title: Keystone dashboard 
      entries:
        - title: View Keystone dashboard
          url: /integrations/keystone-aiq.html
        - title: View usage details and generate reports
          url: /integrations/aiq-keystone-details.html
        - title: Subscriptions tab
          url: /integrations/subscriptions-tab.html
        - title: Current Usage tab
          url: /integrations/current-usage-tab.html
        - title: Capacity Trend tab
          url: /integrations/capacity-trend-tab.html
        - title: Volumes & Objects tab
          url: /integrations/volumes-objects-tab.html
        - title: Performance tab
          url: /integrations/performance-tab.html
        - title: Assets tab
          url: /integrations/assets-tab.html                                                                           
        - title: Manage Keystone subscriptions from BlueXP
          url: /integrations/keystone-cm.html 
    - title: Keystone STaaS services
      entries:  
        - title: Metrics and definitions
          url: /concepts/metrics.html   
        - title: Quality of Service
          url: /concepts/qos.html 
        - title: Supported storage
          url: /concepts/supported-storage-services.html              
        - title: Supported capacity
          url: /concepts/supported-storage-capacity.html
        - title: Service levels
          url: /concepts/service-levels.html
        - title: Supported capacity for service levels
          url: /concepts/capacity-requirements.html
        - title: Keystone subscription services version 1
          url: /subscription-services-v1.html
        - title: Add-on services
          entries:  
            - title: Advanced data protection
              url: /concepts/adp.html
            - title: Data tiering
              url: /concepts/data-tiering.html
            - title: Equinix powered services
              url: /concepts/equinix.html
            - title: Non-returnable, non-volatile components and SnapLock compliance
              url: /concepts/nrnvc.html
            - title: U.S. Citizen Support (USCS)
              url: /concepts/uscs.html
    - title: Billing
      entries:
        - title: Keystone pricing
          url: /concepts/pricing.html
        - title: Billing based on committed capacity
          url: /concepts/committed-capacity-billing.html
        - title: Metering based on consumed capacity
          url: /concepts/consumed-capacity-billing.html
        - title: Billing based on burst consumption
          url: /concepts/burst-consumption-billing.html
        - title: Billing based on miscellaneous volume types
          url: /concepts/misc-volume-billing.html
        - title: Billing schedules
          url: /concepts/billing-schedules.html
    - title: Partner and customer-operated environments
      url: /concepts/operational-models.html
    - title: Keystone infrastructure
      entries:
       -  title: Infrastructure details
          url: /concepts/infra.html
       -  title: Components
          url: /concepts/components.html
       -  title: Data flow
          url: /concepts/data-flow.html
    - title: NetApp Global Services Support Center
      url: /concepts/gssc.html
    - title: Legal notices
      url: /legal-notices.html