---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Keystone docs
      url: "/index.html"
    - title: Release notes
      entries:
        - title: What's new in Keystone STaaS
          url: /release-notes/whats-new.html
        - title: Fixed issues
          url: /release-notes/fixed-issues.html  
        - title: Known limitations
          url: /release-notes/known-limitations.html
        - title: Known issues
          url: /release-notes/known-issues.html  
    - title: Welcome to Keystone
      url: /concepts/overview.html
    - title: Set up and configure Keystone
      entries:
        - title: What is Keystone Collector
          url: /installation/installation-overview.html
        - title: Prepare your system
          entries:
            - title: VMware vSphere requirements
              url: /installation/vapp-prereqs.html
            - title: Linux requirements
              url: /installation/linux-prereqs.html
            - title: ONTAP and StorageGRID requirements
              url: /installation/addl-req.html
        - title: Install Keystone Collector
          entries:
            - title: VMware vSphere deployment
              url: /installation/vapp-installation.html
            - title: Linux installation
              url: /installation/linux-installation.html
            - title: Automatic integrity validation
              url: /installation/validation.html
        - title: Configure Keystone Collector
          url: /installation/configuration.html
        - title: Monitor system health
          url: /installation/monitor-health.html
        - title: Upgrade Keystone Collector
          url: /installation/upgrade.html
        - title: Configure AutoSupport for Keystone
          url: /installation/asup-config.html
        - title: Data collected for billing
          url: /installation/data-collection.html
    - title: View Keystone dashboard and manage subscriptions
      entries:
        - title: View Keystone dashboard on Active IQ Digital Advisor
          entries:
            - title: Keystone and Digital Advisor dashboard
              url: /integrations/keystone-aiq.html
            - title: View consumption details and generate reports
              url: /integrations/aiq-keystone-details.html
            - title: Subscriptions tab
              url: /integrations/subscriptions-tab.html
            - title: Current Usage tab
              url: /integrations/current-usage-tab.html
            - title: SLA Details tab
              url: /integrations/sla-details-tab.html
            - title: Capacity Trend tab
              url: /integrations/capacity-trend-tab.html
            - title: Volumes & Objects tab
              url: /integrations/volumes-objects-tab.html
            - title: Performance tab
              url: /integrations/performance-tab.html
            - title: Assets tab
              url: /integrations/assets-tab.html                                                                           
        - title: Manage Keystone subscriptions from BlueXP
          url: /integrations/keystone-cm.html 
    - title: Learn about Keystone
      entries:    
        - title: Supported storage capacity
          url: /concepts/supported-storage-capacity.html
        - title: Metrics and definitions
          url: /concepts/metrics.html
        - title: Supported storage in Keystone
          url: /concepts/supported-storage-services.html
        - title: Service levels in Keystone
          url: /concepts/service-levels.html
        - title: Add-on Services
          entries:
            - title: Add-on services in Keystone STaaS
              url: /concepts/add-on.html          
            - title: Data tiering
              url: /concepts/data-tiering.html
            - title: Advanced data protection
              url: /concepts/adp.html
            - title: U.S. Citizen Support (USCS)
              url: /concepts/uscs.html
            - title: Non-returnable, non-volatile components and SnapLock compliance
              url: /concepts/nrnvc.html
            - title: Keystone and Equinix
              url: /concepts/equinix.html
    - title: More about Service Levels
      entries:
        - title: Quality of Service
          url: /concepts/qos.html
        - title: Capacity requirements for Service Levels
          url: /concepts/capacity-requirements.html
        - title: Sustainability SLA
          url: /concepts/sla-sustainability.html    
    - title: Billing
      entries:
        - title: Keystone pricing
          url: /concepts/pricing.html
        - title: Billing based on committed capacity
          url: /concepts/committed-capacity-billing.html
        - title: Metering based on consumed capacity
          url: /concepts/consumed-capacity-billing.html
        - title: Billing based on burst consumption
          url: /concepts/burst-consumption-billing.html
        - title: Billing based on miscellaneous volume types
          url: /concepts/misc-volume-billing.html
        - title: Billing schedules
          url: /concepts/billing-schedules.html
    - title: Partner and customer-operated environments
      url: /concepts/operational-models.html
    - title: Keystone infrastructure
      entries:
       -  title: Infrastructure details
          url: /concepts/infra.html
       -  title: Components
          url: /concepts/components.html
       -  title: Data flow
          url: /concepts/data-flow.html
    - title: NetApp Global Services Support Center
      url: /concepts/gssc.html
    - title: Legal notices
      url: /legal-notices.html


