---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Keystone docs
      url: "/index.html"
    - title: Release notes
      entries:
        - title: What's new in Keystone STaaS
          url: /release-notes/whats-new.html
        - title: Fixed issues
          url: /release-notes/fixed-issues.html  
        - title: Known issues
          url: /release-notes/known-issues.html  
        - title: Known limitations
          url: /release-notes/known-limitations.html          
    - title: Get started
      entries:
      - title: Learn about Keystone STaaS
        url: /concepts/overview.html
      - title: Keystone infrastructure
        url: /concepts/infra.html
      - title: Keystone Collector
        url: /installation/installation-overview.html
      - title: Components
        url: /concepts/components.html
      - title: Data flow
        url: /concepts/data-flow.html   
      - title: Operational models
        url: /concepts/operational-models.html 
    - title: Set up and configure Keystone
      entries:
        - title: Requirements
          entries:
            - title: Virtual infrastructure
              url: /installation/vapp-prereqs.html
            - title: Linux 
              url: /installation/linux-prereqs.html
            - title: ONTAP and StorageGRID 
              url: /installation/addl-req.html
        - title: Install Keystone Collector
          entries:
            - title: Deploy on VMware vSphere 
              url: /installation/vapp-installation.html
            - title: Install on Linux 
              url: /installation/linux-installation.html
            - title: Automatic validation of Keystone software
              url: /installation/validation.html
        - title: Configure Keystone Collector
          url: /installation/configuration.html
        - title: Install ITOM Collector
          entries:
            - title: Prepare for installation
              url: /installation/itom-prereqs.html
            - title: Install on Linux
              url: /installation/install-itom-linux.html
            - title: Install on Windows
              url: /installation/install-itom-windows.html
        - title: Configure AutoSupport
          url: /installation/asup-config.html
        - title: Monitor and upgrade
          entries:
            - title: Monitor Keystone Collector health
              url: /installation/monitor-health.html
            - title: Upgrade Keystone Collector
              url: /installation/upgrade.html 
        - title: Keystone Collector security
          url: /installation/security.html
        - title: Data collected for billing
          url: /installation/data-collection.html
        - title: Keystone in private mode
          entries:
            - title: Overview
              url: /dark-sites/overview.html
            - title: Prepare for installation
              url: /dark-sites/requirements.html
            - title: Install Keystone Collector
              url: /dark-sites/install-collector.html
            - title: Configure Keystone Collector
              url: /dark-sites/configure-collector.html
            - title: Monitor Keystone Collector health
              url: /dark-sites/monitor.html
    - title: Manage and monitor Keystone subscriptions
      entries:
        - title: Understand Keystone dashboard
          entries:
            - title: Learn about Keystone dashboard
              url: /integrations/dashboard-overview.html
            - title: Get started with Keystone dashboard
              url: /integrations/dashboard-access.html
            - title: Keystone dashboard in BlueXP
              url: /integrations/keystone-bluexp.html
            - title: Keystone dashboard in Digital Advisor
              url: /integrations/keystone-aiq.html
            - title: Search data, generate reports, and view alerts
              url: /integrations/options.html
            - title: Learn about Keystone and BlueXP digital advisor
              url: /integrations/keystone-cm.html  
        - title: View subscription insights 
          entries:         
            - title: View your subscription details
              url: /integrations/subscriptions-tab.html
            - title: View your current consumption details
              url: /integrations/current-usage-tab.html
            - title: View consumption trends 
              url: /integrations/consumption-tab.html
            - title: View your subscription timeline
              url: /integrations/subscription-timeline.html
        - title: View assets
          entries:
            - title: View assets associated with a subscription
              url: /integrations/assets-tab.html
            - title: View assets across multiple subscriptions
              url: /integrations/assets.html
        - title: Modify your subscriptions
          url: /integrations/modify-subscription.html 
        - title: View or cancel subscription request
          url: /integrations/administration-tab.html       
        - title: View volumes and object storage details
          url: /integrations/volumes-objects-tab.html          
        - title: View performance metrics 
          url: /integrations/performance-tab.html                                                                
    - title: Concepts
      entries:
        - title: Keystone STaaS services
          entries:  
            - title: Metrics and definitions
              url: /concepts/metrics.html   
            - title: Storage quality of service
              url: /concepts/qos.html 
            - title: Supported storage
              url: /concepts/supported-storage-services.html              
            - title: Supported capacity
              url: /concepts/supported-storage-capacity.html
            - title: Service levels
              url: /concepts/service-levels.html
            - title: Capacity requirements for service levels
              url: /concepts/capacity-requirements.html
        - title: Add-on services
          entries:  
            - title: Advanced data protection
              url: /concepts/adp.html
            - title: Data Infrastructure Insights
              url: /concepts/data-infra-insights.html
            - title: Data tiering
              url: /concepts/data-tiering.html
            - title: Equinix powered services
              url: /concepts/equinix.html
            - title: Non-returnable, non-volatile components, and SnapLock compliance
              url: /concepts/nrnvc.html
            - title: U.S. Protected Support (USPS)
              url: /concepts/usps.html 
        - title: Keystone STaaS SLA
          entries:
            - title: Availability
              url: /concepts/sla-availability.html
            - title: Performance
              url: /concepts/sla-performance.html                       
            - title: Sustainability 
              url: /concepts/sla-sustainability.html 
            - title: Ransomware Recovery Guarantee 
              url: /concepts/sla-ransomware.html
        - title: Billing
          entries:
            - title: Keystone pricing
              url: /concepts/pricing.html
            - title: Billing based on committed capacity
              url: /concepts/committed-capacity-billing.html
            - title: Metering based on consumed capacity
              url: /concepts/consumed-capacity-billing.html
            - title: Billing based on burst consumption
              url: /concepts/burst-consumption-billing.html
            - title: Miscellaneous scenarios for Keystone billing
              url: /concepts/misc-volume-billing.html
            - title: Billing schedules
              url: /concepts/billing-schedules.html
    - title: Access Keystone from Digital Advisor REST API
      entries:
        - title: Get started using the Digital Advisor REST API to retrieve Keystone data
          url: /rest-api/retrieve-keystone-data-with-digital-advisor-rest-api.html
        - title: Generate refresh and access tokens
          url: /rest-api/generate-tokens.html                       
        - title: Get a list of all customers using the Digital Advisor REST API 
          url: /rest-api/get-customer-list.html 
        - title: Get customer subscriptions using the Digital Advisor REST API
          url: /rest-api/get-customer-subscriptions.html
        - title: Get customer consumption details using the Digital Advisor REST API
          url: /rest-api/get-customer-consumption.html 
    - title: Keystone subscription services version 1
      url: /subscription-services-v1.html 
    - title: Get help with Keystone
      url: /concepts/gssc.html
    - title: Legal notices
      url: /legal-notices.html
