---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Keystone docs
      url: "/index.html"
    - title: Get started
      entries:
        - title: Learn about Keystone
          url: /concepts/overview.html
        - title: Supported storage capacity in Keystone
          url: /concepts/supported-storage-capacity.html
        - title: Metrics and definitions of Keystone Services
          url: /concepts/metrics.html
        - title: Supported storage types in Keystone
          url: /concepts/supported-storage-services.html
        - title: Service Levels in Keystone
          url: /concepts/service-levels.html
        - title: Add-on Services
          entries:
            - title: Data tiering
              url: /concepts/data-tiering.html
            - title: Advanced Data Protection
              url: /concepts/adp.html
            - title: U.S. Citizen Support (USCS)
              url: /concepts/uscs.html
            - title: Non-returnable, non-volatile components and SnapLock compliance
              url: /concepts/nrnvc.html
            - title: Keystone and Equinix
              url: /concepts/equinix.html
    - title: More about Service Levels
      entries:
        - title: Quality of Service
          url: /concepts/qos.html
        - title: Capacity requirements for Service Levels
          url: /concepts/capacity-requirements.html
    - title: Billing
      entries:
        - title: Keystone pricing
          url: /concepts/pricing.html
        - title: Billing based on committed capacity
          url: /concepts/committed-capacity-billing.html
        - title: Metering based on consumed capacity
          url: /concepts/consumed-capacity-billing.html
        - title: Billing based on burst consumption
          url: /concepts/burst-consumption-billing.html
        - title: Billing based on miscellaneous volume types
          url: /concepts/misc-volume-billing.html
        - title: Billing schedules
          url: /concepts/billing-schedules.html
    - title: Partner and customer-operated environments
      url: /concepts/operational-models.html
    - title: Keystone infrastructure
      entries:
       -  title: Infrastructure details
          url: /concepts/infra.html
       -  title: Components
          url: /concepts/components.html
       -  title: OpsRamp as a monitoring application
          url: /concepts/opsramp.html
       -  title: Data flow
          url: /concepts/data-flow.html
    - title: NetApp Support
      entries:
       -  title: NetApp Global Services Support Center
          url: /concepts/gssc.html
       -  title: NetApp support team operations
          url: /concepts/gssc-ops.html
    - title: Do more with Keystone Services
      entries:
       -  title: Keystone and Cloud Manager
          url: /integrations/keystone-cm.html
       -  title: Keystone and Active IQ	Digital Advisor
          url: /integrations/keystone-aiq.html
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: ???
        - title: What is NetApp Keystone?
          url: /concepts/overview.html
        - title: What are the units of measurement?
          url: /concepts/metrics.html
        - title: What is the supported base storage?
          url: /concepts/supported-storage-services.html
        - title: What is data tiering?
          url: /concepts/data-tiering.html
        - title: Is my Keystone data protected?
          url: /concepts/addon.html#advanced-data-protection
    - title: Service Levels in Keystone
      links:
        - title: Keystone Service Levels
          url: /concepts/service-levels.html
        - title: Quality of Service (QoS)
          url: /concepts/qos.html
        - title: Adaptive Quality of Service (AQoS)
          url: /concepts/aqos.html
        - title: Capacity requirements for Service Levels
          url: /concepts/capacity-requirements.html
    - title: Keystone pricing
      links:
      - title: Know about Keystone billing
        url: /concepts/pricing.html
      - title: My billing schedules
        url: /concepts/billing-schedules.html
      - title: Billing based on committed capacity
        url: /concepts/committed-capacity-billing.html
      - title: Billing based on consumed capacity
        url: /concepts/consumed-capacity-billing.html
      - title: Billing based on burst consumption
        url: /concepts/burst-consumption-billing.html
    - title: Do more with Keystone Services
      links:
        - title: Know your support team (Keystone GSSC)
          url: /concepts/gssc.html
        - title: Keystone and Cloud Manager
          url: /integrations/keystone-cm.html
        - title: Keystone and Active IQ	Digital Advisor
          url: /integrations/keystone-aiq.html
        - title: US Citizen Support
          url: /concepts/uscs.html
    - title: Know more
      links:
        - title: Keystone Flex Subscription
          url: https://docs.netapp.com/us-en/keystone/
        - title: Active IQ Digital Advisor
          url: https://docs.netapp.com/us-en/active-iq/index.html
        - title: Cloud Manager
          url: https://docs.netapp.com/us-en/cloud-manager-family/
        - title: Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/
