---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
    - title: Get started
      entries:
        - title: What's new
          url: ???
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
    - title: Get started
      entries:
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: ???
        - title: What is NetApp Keystone?
          url: /concepts/overview.html
        - title: What are the units of measurement?
          url: /concepts/metrics.html
        - title: What is the supported base storage?
          url: /concepts/supported-storage-services.html
        - title: What is data tiering?
          url: /concepts/addon.html
        - title: Is my Keystone data protected?
          url: /concepts/addon.html
    - title: Storage and object health monitoring
      links:
        - title: Workloads
          url: /storage-mgmt/concept_provision_and_manage_workloads.html
        - title: Virtual infrastructure
          url: /storage-mgmt/concept_monitor_vmware_virtual_infrastructure.html
        - title: MetroCluster configurations
          url: /storage-mgmt/concept_manage_and_monitor_metrocluster_configurations.html
        - title: Clusters and cluster object health
          url: /health-checker/concept_manage_and_monitor_clusters_and_cluster_object_health.html
        - title: Health thresholds
          url: /health-checker/concept_manage_health_thresholds.html
        - title: Send AutoSupport messages and support bundles
          url: /health-checker/task_send_asup_to_technical_support.html
    - title: Data protection monitoring
      links:
        - title: Set up protection relationship
          url: /data-protection/task_set_up_protection_relationships_in_unified_manager.html
        - title: Perform failover and failback
          url: /data-protection/task_perform_protection_relationship_failover_and_failback.html
        - title: Manage protection relationship
          url: /data-protection/concept_manage_and_monitor_protection_relationships.html
        - title: Monitor disaster recovery relationships
          url: /data-protection/task_monitor_storage_vms_using_relationships_page.html
        - title: Generate reports
          url: /reporting/concept_unified_manager_reporting.html
    - title: More resources
      links:
        - title: Unified Manager videos
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
        - title: Unified Manager blogs
          url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
        - title: Documentation for Active IQ Unified Manager 9.10
          url: https://docs.netapp.com/us-en/active-iq-unified-manager-910/
        - title: Documentation for earlier versions
          url: https://docs.netapp.com/ocum-99/topic/com.netapp.ndc.ocum-vers/GUID-DA5B426C-61E1-45E3-B2BE-834636433934.html
