---
sidebar: sidebar
permalink: rest-api/overview.html
keywords: Keystone, ActiveIQ Digital Advisor, APIs, programmatic interface 
summary: The NetApp Keystone ActiveIQ Digital Advisor APIs provide a programmatic interface for fetching Keystone service details and metrics.
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The NetApp Keystone ActiveIQ Digital Advisor APIs provide a programmatic interface for fetching Keystone service details and metrics.

== High Level Overview
The NetApp Keystone ActiveIQ Digital Advisor APIs provide a programmatic interface for fetching Keystone service details and metrics. At a high level, the workflow to interact with these APIs involves the following steps:

. Setup up NetApp Active IQ Digital Advisor account
. Understand the two-step authentication process

.. *Generate Refresh Token*: A refresh token is obtained through AIQ console using NetApp credentials. This token is used to ensure continuous access without the need for repeated logins.
.. *Generate Access Token*: Refresh token is used to generate access token. This access token is required to authorize API calls to the AIQ Keystone service and is valid for one hour.
. Execute the API call to fetch the desired data

== Setup up your NetApp Active IQ Digital Advisor account
Contact the sales representative at NetApp to get access to Active IQ Digital Advisor.
