== Other requirements

Ensure that the following generic requirements are met:

=== Networking Requirements

The networking requirements of Keystone Collector are listed in the following table.

[NOTE]
Keystone Collector requires internet connectivity. You can provide internet connectivity by direct routing through default Gateway (via NAT), or through HTTP Proxy. Both variants are described here.

|===

|Source |Destination |Service |Protocol and Ports |Category |Purpose

a|Keystone Collector (for Keystone ONTAP)
a|Active IQ Unified Manager (Unified Manager)
a|HTTPS
a|TCP 443
a|Mandatory (if using Keystone ONTAP)
a|Keystone Collector usage metrics collection for ONTAP
a|Keystone Collector (for Keystone StorageGRID)
a|StorageGRID Admin Nodes
a|HTTPS
a|TCP 443
a|Mandatory (if using Keystone StorageGRID)
a|Keystone Collector usage metrics collection for StorageGRID
a|Keystone Collector (generic)
a|Internet (as per URL requirements given later)
a|HTTPS
a|TCP 443
a|Mandatory (internet connectivity)
a|Keystone Collector software, OS updates, and metrics upload
a|Keystone Collector (generic)
a|Customer HTTP Proxy
a|HTTP Proxy 
a|Customer Proxy Port
a|Mandatory (internet connectivity)
a|Keystone Collector software, OS updates, and metrics upload
a|Keystone Collector (generic)
a|Customer DNS Servers
a|DNS
a|TCP/UDP 53
a|Mandatory 
a|DNS resolution
a|Keystone Collector (generic)
a|Customer NTP Servers
a|NTP
a|UDP 123
a|Mandatory
a|Time synchronization
a|Keystone Collector (for Keystone ONTAP)
a|Unified Manager
a|MYSQL
a|TCP 3306
a|Optional Functionality
a|Performance metrics collection for Keystone Collector
a|Keystone Collector (generic)
a|Customer Monitoring System
a|HTTPS
a|TCP 7777
a|Optional Functionality
a|Keystone Collector health reporting
a|Customer's Operations Workstations
a|Keystone Collector
a|SSH
a|TCP 22
a|Management
a|Access to the Keystone Collector Management
a|NetApp ONTAP Cluster and Node Management Addresses
a|Keystone Collector
a|HTTP_8000, PING
a|TCP 8000, ICMP Echo Request/Reply
a|Optional Functionality
a|Webserver for ONTAP firmware updates


|===

NOTE: The default port for MySQL, 3306, is restricted only to localhost during a fresh installation of Unified Manager, which prevents the collection of performance metrics for Keystone Collector. For more information, see link:addl-req.html[ONTAP requirements].

=== URL access

Keystone Collector needs access to the following internet hosts:

|===

|Address |Reason 
a|https://keystone.netapp.com[^]
a|Keystone Collector software updates and usage reporting
a|https://support.netapp.com[^]
a|NetApp HQ for billing information and AutoSupport delivery

|===
