---
sidebar: sidebar
permalink: concepts/addon.html
keywords: add-on services, add-on
summary: Add-on, additional Services Details
---

= Add-on storage services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can subscribe to these add-on services as a part of your Keystone subscription.
For information about the base storage and cloud storage service, see link:supported-storage-services.html[Supported storage services]

For information about Performance Service Levels, see link:performance-service-levels.html[Performance Service Levels in Keystone]

== Data tiering
NetApp Keystone (Keystone) service includes a tiering capability with your subscribed file and block services that identifies less-frequently used data and tiers it to a cold storage that is owned, deployed, and managed by NetApp.
[NOTE]
Data tiering to NetApp storage target is included by default in file and block storage service tiers. The add-on service is required only when data is tiered any non-NetApp storage, such as AWS S3, Azure Blob, and EMC ECS.

The tiering capability leverages the NetApp FabricPool technology that enables automated tiering of data to low-cost object storage tiers either on or off premises. With this capability, infrequently accessed data is automatically tiered to a lower cost storage either on premises or in the cloud, based on the services agreed upon.

The tiering service enables tiering from Extreme, Premium, Performance, Standard, and Value tier to Object target. The hot tier and cold tier are metered and invoiced separately. Data tiering can be added any time, without change in pricing and adds more flexibility in terms of hot:cold ratio.

Go through the following calculations for understanding this better:

If the target for cold storage tier is:

*	Value tier (up to 500TiB), Object Tier (>500TiB), existing SGWS grid (customer owned) – There is no additional charge, and it is part of basic storage service.
*	Public cloud (AWS, Azure, Google) and any other third-party supported object storage – There is an additional charge for data capacity that is committed as a tier out charge.

The charges involved in the add-on tiering subscription is not a one-time charge and you need to pay for it for the entire term to sustain the tiering relationship between Keystone on-premises file and block services and the third-party supported object storage target.

This offering only provides the capability to tier cold data to cheaper target storage, not the public cloud/hyperscalar infrastructure costs.
[NOTE]
Hyperscalar-based compute and storage infrastructure are not provided by NetApp as a part of your Keystone subscriptions, and you need to procure them from a hyperscalar cloud service provider.

== Advanced data protection
Keystone advanced data protection service can back up your data and is able to recover it if required. This features leverages the MetroCluster configuration between two sites to enable data protection. You can avail advanced data protection add-on services for only your file and block storage services.
For information about ONTAP MetroCluster, see link:https://docs.netapp.com/us-en/ontap-metrocluster[MetroCluster Documentation]

The add-on charges are applicable to all the capacities in the subscription, that is the source, mirrored copy, and unmirrored data.

Note the following:

* For this service,	100% of the committed capacity on an associated storage service is configured as committed capacity.
*	Storage is charged for both the source and the destination clusters. This add-on service is also charged for both the primary and secondary volumes.
*	The charges are applicable to only your file and block storage services.

== Non-returnable, non-volatile components (NRNVC)

As a part of NetApp Keystone subscription, NetApp extends the non-returnable, non-volatile components (NRNVC) offering for your file, block, and object services.
NetApp does not recover the physical storage media used during the entire service tenure or at service termination when NetApp otherwise recovers all of its physical assets used in the delivery of the service.

If you have purchased this service, note the following:

* You do not need to return any drives and nonvolatile memory at end of the service term or if they failed or found defective during the service term.
* However, you need to produce a certificate of destruction for the drives and/or nonvolatile memory and cannot be used for any other purpose.
* The additional cost associated with the NRNVC is charged as a percentage of the total storage service (includes storage service, Advanced Data Protection, and data tiering) monthly bill.
* This service is applicable for only file, block, and object services.
