---
sidebar: sidebar
permalink: concepts/billing-schedules.html
keywords: billing schedules, schedule for payment
summary: Keystone STaaS subscriptions are billed monthly and yearly.
---

= Billing schedules
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone STaaS subscriptions in version 3 are billed on a monthly, quarterly, semi-annual, or annual basis.

== Monthly billing
Invoices are sent monthly. For the month in which the services are availed, an invoice is sent in the next month. For example, the invoice for the services you have used in January is delivered at the beginning of February. This invoice includes the charges for the committed capacity and if applicable, any burst usage.

== ##Quarterly, semi-annual, and annual billing##
For quarterly, semi-annual, and annual billing, the process is similar with slight variations in timing:

* *Quarterly billing*: An invoice is generated at the beginning of each subscription quarter for the minimum payment of the committed capacity. Another invoice is sent at the end of the quarter for any burst usage accrued.
* *Semi-annual billing*: An invoice is generated at the beginning of every six months for the minimum payment of the committed capacity. Another invoice is sent at the end of each quarter for any burst usage accrued.
* *Annual billing*: An invoice is generated at the beginning of each subscription year for the minimum payment of the committed capacity. Another invoice is sent at the end of each quarter for any burst usage accrued.

For quarterly, semi-annual, and annual billing, if the committed capacity is changed during a subscription, an invoice is sent on the same day for the prorated minimum payments for the rest of that subscription year. The billing is calculated from the day when the change in the committed capacity is effective. 




