---
sidebar: sidebar
permalink: concepts/equinix.html
keywords: netapp, keystone, Equinix
summary: Keystone Flex Subscription and Equinix
---

= Keystone co-location services powered by Equinix
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp has partnered with Equinix for hosting NetApp Keystone services in an Equinix data center to ensure the delivery of a unified solution for you.

Keystone co-location (Co-Lo) services powered by Equinix is unchanged from the standard Keystone service offering.

In this service:

* Equinix provides space, power, cooling, networking, and invoice, and storage, on a monthly basis.
*	Support is provided for to certain Keystone sales motions.
*	The services are supported in 21 data centers across 11 countries.

Equinix has the data centers at these locations:

|===
|Data center |Country

a| Amsterdam | Netherlands
a| Atlanta |U.S.
a| Chicago |U.S.
a| Dallas |U.S.
a| Denver |U.S.
a| Frankfurt |Germany
a| London |U.K.
a| Lost Angeles |U.S.
a| Madrid |Spain
a| Melbourne |Australia
a| Miami |U.S.
a| Milan |Italy
a| Osaka |Japan
a| Paris |France
a| Seattle |U.S.
a| Silicon Valley |U.S.
a| Sydney |Australia
a| Tokyo |Japan
a| Toronto |Canada
a| Washington DC |U.S.
a| Zurich |Switzerland

|===
