---
sidebar: sidebar
permalink: concepts/gssc.html
keywords: Global Services Support Center, GSSC, Keystone support
summary: NetApp Global Services Support Center GSSC
---

= NetApp Global Services Support Center
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Keystone services are run by leveraging the NetApp Global Services and Support Center (GSSC), NetApp Keystone Success Manager, and NetApp Keystone Service Delivery Manager.

== NetApp Global Services and Support Center (GSSC)
NetApp provides operational services remotely to NetApp Keystone customers. These services encompass a range of operational disciplines across storage management activities. These services include asset and configuration management, capacity and performance management, change management, event, incident and problem management, service request fulfillment, and reporting. NetApp demonstrates a state of control and supporting evidences as required.

== Additional Information and Support Contact
The NetApp Global Services and Support Center (GSSC) team primarily support the services to NetApp Keystone customers. You can use the following information to reach out to the support team.

* Global service contacts :
https://www.netapp.com/us/contact-us/support.aspx

* If you have an open case/ticket that needs to be escalated, send an email to one of the following addresses:
keystone.services@netapp.com
keystone.escalations@netapp.com

* NetApp uses OpsRamp, a cloud-based remote gateway solution to proactively monitor and connect to the NetApp Keystone environment for troubleshooting. For information on OpsRamp, see https://www.opsramp.com/#.

[NOTE]
In a partner-operated model, the tenant and subtenant's service requests are assigned to the partner's service desk. The partner's support tool might have integration with OpsRamp and GSSC applications. Only L3 issues are escalated to NetApp through GSSC.

For more information, see:

* NetApp Keystone
 https://www.netapp.com/us/solutions/keystone/index.aspx[https://www.netapp.com/us/solutions/keystone/index.aspx^]
* NetApp Product Documentation
 https://docs.netapp.com[https://docs.netapp.com^]

== GSSC monitoring
NetApp Global Services and Support Center (GSSC) monitors the health of your products and subscribed services, provides remote support, and collaborates with your Keystone Success Manager. All personnel monitoring the products associated with the relevant Keystone subscription orders are U.S citizens operating on U.S. soil.

.Keystone Success Manager
The Keystone Success Manager is a U.S. citizen operating on U.S. soil. The responsibilities are specified in your NetApp Keystone Agreement.

For information, see link:../concepts/uscs.html[U.S. Citizen Support (USCS)].



