---
sidebar: sidebar
permalink: concepts/metrics.html
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3
summary: The NetApp Keystone STaaS service uses several terms to measure metrics. You might want to learn more about these terms as you use Keystone for version 3 of the service.
---

= Understand storage metrics and definitions in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
##Learn the key terms Keystone STaaS uses to measure and report on your storage subscription, including capacity units, performance metrics, and availability definitions.##

== Metrics measurement

* *Capacity measurement in GiB, TiB, and PiB*: Measurements of data storage capacity using base of 1024 (1 GiB = 1024^3^ bytes, 1 TiB = 1024^4^ bytes, and 1 PiB = 1024^5^ bytes).
* *Operations counter chart in IOPS*: The protocol operations per second, requested by the application.
* *Availability*: Measured as a percentage of the number of I/O requests successfully responded to by the service, divided by total number of I/O requests made to the service. This is measured at the service demarcation in a month and does not include the scheduled service downtime or unavailability of the facilities, network, or other services provided by the customer.
* *Durability*: Percentage of data accessed without loss of fidelity, excluding customer-caused deletion or corruption.
* *Latency*: Time to service an I/O request received from a client, measured at the service demarcation (storage controller I/O port).
* *Throughput*: ##<must review the definition>The amount of data transferred per second, measured in GBps (gigabytes per second), measured at the storage controller I/O port.##

