---
sidebar: sidebar
permalink: concepts/metrics.html
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3
summary: The NetApp Keystone STaaS service uses several terms to measure metrics. You might want to learn more about these terms as you use Keystone for version 3 of the service.
---

= Metrics and definitions used in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
##The NetApp Keystone STaaS service uses several terms to measure metrics. You might want to learn more about these terms as you use Keystone for version 3 (v3).##

The following terms and definitions are used within the Keystone STaaS service to measure metrics:

* Capacity measurement units: GiB, TiB, and PiB
* IOPS: Number of input/output operations processed per second.
* Service availability
* Durability in accurate data access
* Latency and speed

== Metrics measurement

* *Capacity measurement in gibibyte (GiB), tebibyte (TiB), and pebibyte (PiB)*: Measurements of data storage capacity using base of 1024 (1 GiB = 1024^3^ bytes, 1 TiB = 1024^4^ bytes, and 1PiB = 1024^5^ bytes).
* *Operations counter chart in IOPS*: ##The protocol operations per second, requested by the application.##
* *Availability*: Measured as a percentage of the number of I/O requests successfully responded to by the service, divided by total number of I/O requests made to the service. This is measured at the service demarcation in a month and does not include the scheduled service downtime or unavailability of the facilities, network, or other services provided by the customer.
* *Durability*: Percentage of data accessed without loss of fidelity, excluding customer-caused deletion or corruption.
* *Latency*: Time to service an I/O request received from a client, measured at the service demarcation (storage controller I/O port).

=== ##Performance metrics##
The following performance metrics are applicable for unified and block optimized services:

* *IOPS*: Random I/O operations, 70% read and 30% write, using an 8 KB block size.
* *Throughput*: Sequential I/O operations, 100% read, using a 32 KB block size.

=== (Deprecated) Throughput performance metrics
Throughput performance metrics are applicable only for file and block services based on:

*	32 KB block sizes
*	70% read/30% write I/O mix

=== (Deprecated)Variations in IO density
IO density calculated in IOPS/TiB and/or MBps/TiB varies based on the following factors:

*	Workload characteristics
*	Latency, excluding the following:
** Application latency
** Host latency
** Latency in the customer network while transferring data to and from the controller ports
** Overhead latency associated with data transfer to the object store in the case of FabricPool
** The latency automatically applied by the QoS to keep IO within service level maximums
*	The user and Snapshot copy data that is counted as part of the used capacity
*	The allocated absolute minimum IOPS on each ONTAP volume, regardless of the amount of data in the volume:
** Extreme: 1,000 IOPS
** Premium: 500 IOPS
** Performance, Standard, and Value: 75 IOPS
*	While using the Advanced Data Protection add-on services, the target latency applies only to servicing IO requests from the local storage.

=== (Deprecated) Volume AQoS
Each ONTAP volume should have the applicable adaptive quality of service (AQoS) policy applied. Otherwise, the capacity within each volume that does not have an AQoS policy applied is billed at the rate of the highest Service Level.
