---
sidebar: sidebar
permalink: concepts/misc-volume-billing.html
keywords: Keystone billing, special volume types, cloned volumes, SnapMirror destinations, LUNs, temporary volumes
summary: Keystone billing rules differ for certain volume configurations. This page explains billing for cloned volumes, SnapMirror destinations, LUNs, temporary volumes, and system volumes.
---

= Keystone billing for specific volume types
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone billing rules differ for certain volume configurations. Knowing these exceptions helps you avoid unexpected charges when working with cloned volumes, SnapMirror destinations, LUNs, or temporary storage.

The following table summarizes the billing rules for each volume type.

[cols="1,2",options="header"]
|===
|Volume type |Billing rule

|Cloned volumes
|Free if less than 10% of parent volume size; standard billing above that threshold

|Temporary volumes
|Not billed

|SnapMirror destinations
|Billed at the destination performance service level

|LUNs
|Billed at the performance service level of the containing volume

|System and root volumes
|Monitored but not billed
|===

== Billing for cloned volumes
Cloning is commonly used for backups and restores. Keystone treats backup-purpose clones differently from those used for other ongoing business operations.

If volumes are cloned in ONTAP and you use them for backing up and restoring your data, you can continue using the clones without any additional payments. However, cloned volumes used for any other purpose in your business for an extensive duration are charged.

Note the following:

* Clone volumes are not billed as long as their size is less than 10% of the parent volume (the physical capacity used in the clone volume compared to the physical capacity used in the parent volume).
* There is no 24-hour grace period for cloned volumes. Only the size of the clone is considered.
* Once the clone volume exceeds 10% of the physical size of the parent, the clone is billed as a standard volume (logical used capacity).

//== Billing for advanced data protection
//Advanced data protection uses NetApp MetroCluster to mirror data between two physically separated clusters. For MetroCluster mirrored aggregates, data is written twice, once on each cluster. The Keystone service charges for consumption on each side independently, resulting in two identical consumption records. The add-on charges are applied on all the capacities in the subscription, irrespective of whether the data is at the source, or it is mirrored or unmirrored data.

//If you monitor your clusters through ONTAP System Manager (System Manager) or Active IQ Unified Manager (Unified Manager), you might see a discrepancy between the consumption reported on these tools and Keystone. System Manager and Unified Manager do not report volumes on the mirrored (remote) cluster, and in doing so, reports half the consumption metrics that the Keystone service reports.

//.Example:
//Site A and Site B are set up in a MetroCluster configuration. When a user creates a volume of 10TB in site A, an identical volume of 10TB is created in site B. Keystone identifies 10TB of consumption in each site, for a total increase of 20TB. System Manager and Unified Manager report a 10TB volume created in site A, but do not report a 10TB volume in Site B.

//Additionally, all volumes created on a Keystone system with advanced data protection will be counted towards the consumption of advanced data protection, regardless of whether those volumes are mirrored or not.

== Billing for temporary volumes
Occasionally, temporary (TMP) volumes are created by ONTAP when moving volumes. These temporary volumes are short-lived, and the consumption on these volumes is not measured for billing.

== Billing for SnapMirror destinations
The pricing for SnapMirror destination volumes, whether used for disaster recovery or long-term retention, is based on the performance service level assigned to the destination. There is no extra fee for data protection.

== Billing for LUNs
For LUNs, the billing is based on the performance service levels of the volume.

== System and root volumes
System and root volumes are monitored as a part of the overall monitoring of the Keystone service but are not counted or billed. The consumption on these volumes is exempted for billing.

