---
sidebar: sidebar
permalink: concepts/pricing.html
keywords: pricing, billing introduction, Keystone billing
summary: Keystone offers a pay-as-you-grow model for your flexible and scalable consumption needs.
---

= Keystone pricing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you prefer an operational expenditure (OpEx) consumption model over capital expenditure (CapEx) or leasing, you can opt for the NetApp Keystone STaaS pay-as-you-grow model, which offers flexible and scalable consumption with predictable and upfront pricing for your storage subscription.

Keystone provides you with the following billing facilities:

* You can pay based on IOPS and latency committed capacity to meet various workload needs. The different performance service tiers - Extreme, Premium, Performance, Standard, Value, and Object enable you to manage your storage based on your purchased service level.
* It presents predictable billing for the committed capacity and pay-per-use for variable (burst) capacity usage.
* You can select a bundle price for hardware, core OS, and support for one $/TiB price. You have a single invoice for each storage type, file, block, object, or cloud storage services.
* Select a flexible term for the services and payment: You can opt for 12 months, 25TiB, or more per site. Thereafter, you can auto renew for 12 months.

Keystone billing is based on committed capacity and variable burst consumption.

For information about different capacities supported in Keystone, see link:../concepts/supported-storage-capacity.html[Supported storage capacities in Keystone].

*Related information*

* link:../concepts/committed-capacity-billing.html[Billing based on committed capacity]
* link:../concepts/consumed-capacity-billing.html[Metering based on consumed capacity]
* link:../concepts/burst-consumption-billing.html[Billing based on burst consumption]
* link:../concepts/misc-volume-billing.html[Billing based on miscellaneous volume types]
* link:../concepts/billing-schedules.html[Billing schedules]
