---
sidebar: sidebar
permalink: concepts/service-levels.html
keywords: service levels, service level, rate plan or service level
summary: Keystone STaaS for version 3 offers storage capacity at pre-defined service levels. Each volume managed by Keystone is associated with a service level.
---

= Performance service levels in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone STaaS offers data storage capacity at pre-defined performance service levels (PSLs). Each volume managed by Keystone services is associated with a performance service level.

A subscription can have multiple rate plans and each rate plan corresponds to a performance service level. Each rate plan has a committed capacity per performance service level. 

##<must review> Each performance service level can have multiple instances in your environment, with each instance representing a separate storage system assigned to that performance service level. For unified or block-optimized storage, an instance is a storage array (a data storage device consisting of two storage controllers in an HA pair and dedicated internal or externally attached storage media). For AFX storage, an instance is an AFX storage controller. Performance metrics such as input/output operations per second (IOPS), throughput (GBps), and latency (ms) are measured and applied per instance.##

You select performance service levels based on your storage environment and consumption needs. The base performance service levels are available by default. Specific performance service levels are additionally available if you have opted for add-on services.

//For example, for the advanced data protection add-on service, the _Advanced Data-Protect_ performance service level is assigned to your subscription.

[TIP]
A detailed service description for NetApp Keystone STaaS performance service levels is available https://www.netapp.com/services/keystone/terms-and-conditions/[here^].

The base performance service levels for the supported data storage types: unified, block-optimized, AFX, object, and cloud services are described in the following sections:

== ##Performance service levels for unified storage##
*Supported protocols*: FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3

|===
|*Performance service level*
(all specifications per performance service level instance [HA pair])|*Extreme* |*Premium* |*Standard* |*Value*
|*Sample workload types* |AI/ML, HPC, InMem DB |Analytics, EDA, OLTP | OLAP, IoT, Containers |Backup, Archive
|*Target 90^th^ percentile latency* | &lt;=1 ms | &lt;=1 ms | &lt;=4 ms | >4 ms 
|*Target maximum IOPS*^1^ |1M |550K |250K | NA
|*Target maximum GBps*^1^ |40  |20 |10 | NA
|*Platform* |AFF A-Series |AFF A-Series |AFF C-Series | FAS
|*Minimum committed capacity* | 50 TiB | 50 TiB | 100 TiB | 100 TiB
|*Incremental committed capacity increase*
4+| 25 TiB
|*Committed and metered capacity type*
4+|Logical or physical
|===

== ##Performance service levels for block-optimized storage##
*Supported protocols*: NVMe/TCP, NVMe/FC, FC, iSCSI

|===
|*Performance service level*
(all specifications per performance service level instance [HA pair])|*Extreme* |*Premium* | *Standard* 
|*Sample workload types*
3+| SAP HANA, Oracle, MS SQL Server, EPIC
|*Target 90^th^ percentile latency* | &lt;=1 ms | &lt;=1 ms | &lt;=4 ms
|*Target maximum IOPS*^1^|850K |450K | 120K
|*Target maximum GBps* |65  |25 | 6
|*Platform* |ASA A-Series |ASA A-Series |ASA C-Series 
|*Minimum committed capacity* | 50 TiB | 50 TiB | 100 TiB
|*Incremental committed capacity increase*
3+| 25TiB
|*Committed and metered capacity type*
3+| Logical or physical
|===

== ##Performance service levels for AFX storage##
*Supported protocols*: NFSv3, NFSv4/RDMA, pNFS, SMB, S3

|===
|*Performance service level*
(all specifications per performance service level instance [one AFX storage controller])|*Extreme* 
|*Sample workload types*| AI/ML, HPC, InMem DB
|*Target 90^th^ percentile latency* | &lt;=1 ms
|*Target maximum IOPS*^1^|625K
|*Target maximum GBps* |20
|*Platform* |AFX
|*Minimum committed capacity per AFX cluster* | 200 TiB  
|*Incremental committed capacity increase* | 100 TiB
|*Committed and metered capacity type*| Physical
|===

NOTE: ^1^Mutually exclusive targets. Actual performance may differ based on various factors, including the operating system version, hardware, workload type, and number of concurrent operations.

=== More on performance service levels for unified, block-optimized, and AFX storage

The base performance service level metrics depend on the following conditions:

* The performance service levels support ONTAP 9.8 and later.
* For unified storage, 
+
** *IOPS*: For ONTAP 9.16.1 with NFS, each performance level instance supports random access with a 70% read and 30% write ratio, an 8 KB block size, and a latency of 1 ms (4 ms for Standard).
** *Throughput*: For ONTAP 9.16.1 with NFS, each performance level instance supports sequential access with 100% read and a 32 KB block size.
* For block-optimized storage,
+
** *IOPS*: For ONTAP 9.16.1 with FCP, each performance level instance supports random access with a 70% read and 30% write ratio, an 8 KB block size, and a latency of 1 ms.
** *Throughput*: For ONTAP 9.16.1 with FCP, each performance level instance supports sequential access with 100% read and a 64 KB block size.
* ##For AFX storage##,
+
** *IOPS*: For ONTAP 9.18.1 with NFSv4, each performance level instance supports random access with a 70% read and 30% write ratio, and a 4 KB block size.
** *Throughput*: For ONTAP 9.18.1 with NFSv4, each performance level instance supports sequential access with 100% read and a 64 KB block size.
* Latency does not include the following: 
** application or host latency
** customer network latency to or from the controller ports
** overheads associated with the data transfer to the object store in case of FabricPool
* Latency values are not applicable to MetroCluster write operations. These write operations are dependent on the distance of remote systems.
* _Expected IOPS_ is targeted for FabricPool only if the tiering policy is set to "none" and no blocks are in the cloud. _Expected IOPS_ is targeted for volumes that are not in a SnapMirror synchronous relationship.

== Performance service levels for object storage
*Supported protocol*: S3

|===
|*Performance service level* | *Standard* | *Value* 
|*##Platform##* | SGF6112 | SG6160
|*Minimum committed capacity per order* | 200 TiB | 500 TiB 
|*Incremental committed capacity increase* | 25 TiB | 100 TiB
|*Committed and metered capacity type*
2+| Physical
|===

== Cloud storage

*Supported protocols*: NFS, CIFS, iSCSI, and S3 (AWS and Azure only)

|===
|*Performance service level* | *Cloud Volumes ONTAP*
|*##Platform##* | Cloud Volumes ONTAP
|*Minimum committed capacity per order* | 4 TiB  
|*Incremental committed capacity increase* | 1 TiB 
|*Committed and metered capacity type*| Logical
|===

[NOTE]
====
- Cloud native services, such as compute, storage, networking, are invoiced by cloud providers.
- These services are dependent on cloud storage and compute characteristics.
====

*Related information*

* link:../concepts/supported-storage-capacity.html[Supported storage capacities]
* link:..//concepts/metrics.html[Metrics and definitions used in Keystone Services]
* link:../concepts/pricing.html[Keystone pricing]