---
sidebar: sidebar
permalink: concepts/service-levels.html
keywords: service levels, service level
summary: Supported service levels
---

= Service Levels in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone STaaS offers data storage capacity at pre-defined performance service levels (service levels) on a subscription basis. 

Service levels are defined by:

* Average latency
* Maximum IOPS per logical TiB stored per volume

A volume must be associated with a service level.

== Service levels for supported storage
The service levels for file, block, object, and cloud services are listed here.

// I/O density calculations at the volume level are reported to show peak I/O density during the prior week. The peak performance is determined on an hourly time interval. I/O density reports by volume are generated monthly to gauge adherence to the respective service levels.

=== File and block storage
*Supported protocols*: NFS, CIFS, iSCSI, and FC

|===
|*Service level* |*Extreme* |*Premium* | *Performance* |*Standard* |*Value*
|*Sample workload types* |Analytics, databases, mission-critical apps |VDI, VSI, software development | OLTP, OLAP, containers, software development
 |File shares, web servers |Backup
|*Maximum IOPS/logical TiBs stored per volume* |12,288 |4,096 |2,048 | 512 |128
|*Maximum MBps/logical TiBs stored per volume* |384 |128 |64 |16 |4
|*Latency* |<1 ms |<2 ms |<4 ms |<17 ms |<17 ms

|===

[NOTE]
Note the following points for throughput performance metrics (applicable only for file and block services):

* File and block service levels are based on ONTAP 9.7 and later.
* IOPS/TiB and latency values for service levels are based on the amount of logical data stored in the volume, 32 KB block size, and a random mix of 70% read and /30% write IO.
* Actual IOPS/TiB and/or MBps/TiB varies based on workload concurrency and usage patterns.
* Latency does not include the following:
** The applications, hosts, or customer network latency to or from the controller ports.
** The latency automatically applied by QoS to keep IO within service level maximums.
* When using the Advanced Data Protection add-on service, the target latency applies to servicing IO requests from the local Keystone products only.

=== Object storage
*Supported protocol*: S3

|===
|*Service level* | Object
|*Workload type* |Media repository, archiving
|*Maximum IOPS/logical TiB stored per volume*
|N/A
|*Maximum MBps/logical TiB stored per volume* |N/A
|*Average Latency* |N/A

|===

[NOTE]
Latency does not include overheads associated with data transfer to the object store in case of FabricPool storage.

=== Cloud storage
*Supported protocol*: NFS, CIFS, iSCSI, and S3 (AWS and Azure only)

|===
|*Service level* | Cloud Volumes ONTAP®
|*Workload type* |Disaster Recovery, software development/testing, business apps
|*Maximum IOPS/logical TiB stored per volume*
|N/A
|*Maximum MBps/logical TiB stored per volume* |N/A
|*Average Latency* |N/A

|===

[NOTE]
Note:

* Cloud native services, such as compute, storage, networking, are invoiced by the cloud providers.
* These services are dependent on the cloud storage and compute characteristics.
