---
sidebar: sidebar
permalink: concepts/service-levels.html
keywords: service levels, service level
summary: Supported service levels
---

= Service Levels in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone STaaS offers data storage capacity at pre-defined performance service levels (service levels) on a subscription basis. 

Service levels are defined by:

* Average latency
* Maximum IOPS per logical TiB stored per volume

Each volume needs to be associated with a service level.

== Service levels for difference storage types
The service levels for file, block, object, and cloud services are listed here.

I/O density calculations at the volume level are reported to show peak I/O density during the prior week. The peak performance is determined on an hourly time interval. I/O density reports by volume are generated monthly to gauge adherence to the respective service levels.

=== File and block services
*Supported protocols*: NFS, CIFS, iSCSI, and FC

|===
|*Service level* |*Extreme* |*Premium* | *Performance* |*Standard* |*Value*
|*Workload type* |Analytics, databases, mission-critical apps |VDI, VSI, software development | OLTP, OLAP, containers, software development
 |File shares, web servers |Backup
|*Max IOPS/TiB* |12,288 |4,096 |2,048 | 512 |128
|*Max throughput MBps/TiB* |384 |128 |64 |16 |4
|*Latency* |<1 ms |<1 ms |<1 ms |<17 ms |<17 ms

|===

[NOTE]
Note:

* Throughput performance metrics (applicable only to file and block services) are based on:
** 32KB block sizes
** 70% read/30% write IO mix
* Actual IOPS/TiB and/or MBps/TiB varies based on workload characteristics.
* Latency does not include application, host, or customer network latency to or from the controller ports.

=== Object storage
*Supported protocol*: S3

|===
|*Service level* | Object
|*Workload type* |Media repository, archiving
|*Target IOPS/TiB*
|N/A
|*Max IOPS/TiB* |N/A
|*Max throughput MBps (32KB/IOP)* |N/A
|*Latency* |N/A

|===

[NOTE]
Note:

* Actual IOPS/TiB and/or MBps/TiB varies based on workload characteristics.
* Latency does not include application, host, or customer network latency to or from the controller ports.

=== Cloud storage
*Supported protocol*: NFS, CIFS, iSCSI

|===
|*Service level* | Cloud Volumes ONTAP®**
(all cloud)
|*Workload type* |Disaster Recovery, software development/testing, business apps
|*Target IOPS/TiB*
|N/A
|*Max IOPS/TiB* |N/A
|*Max throughput MBps (32KB/IOP)* |N/A
|*Latency* |N/A

|===

[NOTE]
Note:

* Cloud native services, such as compute, storage, networking, are invoiced by the cloud providers.
* These services are dependent on the cloud storage and compute characteristics.
