---
sidebar: sidebar
permalink: concepts/sla-availability.html
keywords: availability, sla, service level agreement, 
summary: availability, sla, service level agreement
---

= Availability SLA for Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp offers Service Level Agreements (SLAs) for ensuring continuous uptime of your systems governed by Keystone STaaS. Availability SLA ensures to provide at least 99.999% average uptime during a billing period across all NetApp AFF storage arrays for your Keystone StaaS subscriptions.

The failover events are calculated 15 seconds after the failover till the HA failover is complete, after which it is considered as a system downtime. The capacity affected during the downtime is also measured, in terms of the affected nodes and volumes, and on an SLA breach credits would be calculated and issues proportionately based on the committed capacity of the respective service level. 


== Service levels of availability SLA
The service levels for NetApp AFF Storage platform are eligible for availability SLA. This includes the service levels for file and block storage, that is Extreme, Performance, Premium, and Standard service levels. 

For information about service levels, see link:../concepts/service-levels.html[Service Levels in Keystone].

== Availability metrics
The metrics for availability and uptime SLA is considered 

monthly uptime percentage = [(maximum available minutes – downtime) / maximum available minutes] x 100%
maximum available minutes = total number of minutes in a billing period
downtime = the period of time during which both controllers, within an HA pair of a Storage Array, are unavailable, as determined by NetApp, excluding a period of time when the Subscription Services are not available due to scheduled or mutually agreed upon time period for NetApp to perform maintenance, upgrades, or support activities, or due to situations outside of NetApp or Keystone Service control or responsibilities.

== Eligibility criteria
Keystone STaaS subscriptions should meet following criteria for being eligible for availability SLAs:

* ONTAP 9.10 and later should be installed. The ONTAP version should not be upgraded or modified during the reported breach.
* New STaaS subscriptions should be nominated and approved by the Keystone sales and internal teams.
* The minimum Annual Contract Value (ACV) should be of $150,000.
* Availability SLAs are applicable to the designated burst usage limit, for example, 120% of the committed capacity of a service level. For information about burst usage, see link:../concepts/supported-storage-capacity.html#burst-capacity[Burst capacity].
* Monitoring tools, controllers and their management ports, AutoSupport tools, and subscription hardware should not be modified, and should be enabled and available for NetApp to manage.
* Data efficiency settings, including compression, compaction, deduplication, and thin provisioning should be enabled.
* The service levels should support AQoS policies and all the eligible volumes have to governed by the AQoS policies.

== Availability SLA reports
The SLA tab on the Active IQ Digital Advisor (Digital Advisor) Keystone dashboard provides a detailed view of the availability metrics for your Keystone subscriptions. You can view the metrics and generate reports for future analysis and actions.

For more information about Keystone dashboard and reporting, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting].

== Availability service credits
If there is an SLA breach that is acknowledged by NetApp, initiate a service credit request within six weeks of the validation of the SLA breach. For requesting service credit, follow these steps:

. Open a priority 3 (P3) support ticket with Keystone Global Services and Support Center (GSSC). For information, see link:../concepts/gssc.html[NetApp Global Services Support Center].
. Wait up to 36 hours for the support team to monitor and troubleshoot the incident. Allow up to 96 hours for the team to fix the incident.
. Meanwhile, for any query, contact GSSC with this information:
** Support ticket number.
** Keystone subscription number. 
** The volumes and storage controller details. 
** Site, time, date, and description of the issue. 
** Calculated time duration of the breach of the SLA. 
** Measurement tools and methods.
** Any other applicable document.

[NOTE]
The service credit is applicable to the invoice raised for your consumed capacity in the next billing cycle for the specific Keystone subscription. Service credit do not apply to expired Keystone subscriptions.




