---
sidebar: sidebar
permalink: concepts/sla-performance.html
keywords: performance, sla, service level agreement, 
summary: performance, sla, service level agreement
---

= Performance SLA for Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The performance-based Service Level Agreement (SLA) of NetApp Keystone STaaS ensures guaranteed performance based on the target latency for the subscribed performance service levels (service levels).

* For each service level, IOPS/TiB and latency values are based on the amount of logical data stored in a volume, data operations IOPS, 32KB block size, and a random mix of 70% read and 30% write IO operations. 
* The MBps values for a service level are based on the amount of logical data stored in a volume, 100% sequential read IO operations, and 32KB block size.
* Performance SLAs are applicable to the designated burst usage limit, for example, 120% of the committed capacity of a service level. For information about burst usage, see link:../concepts/supported-storage-capacity.html#burst-capacity[Burst capacity].


== Service levels of performance SLA
The service levels for NetApp AFF Storage platform are eligible for performance SLA. This includes the service levels for file and block storage, that is Extreme, Performance, Premium, and Standard service levels. 

For information about the latency requirements of the service levels, see link:../concepts/service-levels.html[Service Levels in Keystone].

Performance SLA is based on the following latency definitions of the service levels: 

|===
|*Service level* | Extreme |Premium |Performance |Standard
a|
*Target 90^th^ percentile latency* |<1ms |<2ms |<4ms |<4ms

|===

== Target latency measurement

Target latency is measured by the performance service level (service level) for a volume, and for all the volumes in your Keystone subscription. Latency is sampled every five minutes, and the 90^th^ percentile value over a 24-hour period is used as the daily measure. From the records filtered based on the specified criteria, the 90^th^ percentile of the latency is selected, and if that value is less than the target latency for a service level, performance SLA is considered to have been breached. On an SLA breach credits would be calculated and issues proportionately based on the target latency of the respective service level.

The following points help you understand the metrics collection and measurement:

* Only those volumes that record at least five IOPS at the time of metrics collection are considered for the sample.
* Volumes with greater than 30% write IO operations at the time of metrics collection are excluded from the sample.
* Latency injected by AQoS for the requested IOPs/TiB that is greater than target IOPs/TiB are excluded from the sample.
* Latency injected by AQoS to maintain minimum IOPs per volume is not considered. 
* For volumes that have FabricPool enabled, the latency incurred due to the transfer of data to/from the target (cold) storage is not counted. 
* Latency caused by the application, host, or customer network outside of the ONTAP cluster is not counted.
* When using the Advanced Data Protection add-on service, the target latency includes only IO operations to and from the local storage array.
* During a 24-hour period, at least ten valid metrics should be available. Else, the metrics are discarded.


== Eligibility criteria
Keystone STaaS subscriptions meeting the following criteria are eligible for performance SLAs:

* Service levels supported on ONTAP 9.10 and later.
* Only new STaaS subscriptions that are nominated and approved by the Keystone sales and internal teams.
* The minimum Annual Contract Value (ACV) of $150,000.
* The service levels for performance SLA supporting AQoS policies and all the eligible volumes governed by the AQoS policies.
* All relevant storage arrays are fully utilized, and the CPU load equally distributed across all controllers.
* Monitoring tools, data collectors, and AutoSupport tools are installed and enabled.
* The minimum size of the FlexVol volume is 100 GiB.
* There is a maximum of 1,000 volumes per controller.


== Performance SLA reports
The SLA tab on the Active IQ Digital Advisor (Digital Advisor) Keystone dashboard provides a detailed view of the performance metrics for your Keystone subscriptions. You can view the metrics and generate reports for future analysis and actions.

For more information about Keystone dashboard and reporting, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting].

== Performance service credits
If there is an SLA breach that is acknowledged by NetApp, initiate a service credit request within six weeks of the validation of the SLA breach. For requesting service credit, follow these steps:

. Open a priority 3 (P3) support ticket with Keystone Global Services and Support Center (GSSC). For information, see link:../concepts/gssc.html[NetApp Global Services Support Center].
. Wait up to 36 hours for the support team to monitor and troubleshoot the incident. Allow up to 96 hours for the team to fix the incident.
. Meanwhile, for any query, contact GSSC with this information:
** Support ticket number.
** Keystone subscription number. 
** The volumes and storage controller details. 
** Site, time, date, and description of the issue. 
** Calculated time duration of the breach of the SLA. 
** Measurement tools and methods.
** Any other applicable document.

[NOTE]
The service credit is applicable to the invoice raised for your consumed capacity in the next billing cycle for the specific Keystone subscription. Service credit do not apply to expired Keystone subscriptions.




