---
sidebar: sidebar
permalink: concepts/sla-sustainability.html
keywords: sustainability, sla, service level agreement, 
summary: sustainability, sla, service level agreement
---

= Sustainability SLA for Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
As a part of the Keystone STaaS offering, NetApp establishes a service level agreement (SLA) with you to guarantee accurate reporting of your sustainability score. It provides you with insights to environmental sustainability of your storage assets supported by Keystone services.

NetApp enables you to perform sustainable operations and align your storage systems with eco-friendly practices to achieve sustainability targets. By leveraging various storage efficiency features in ONTAP, cloud tiering, and cloud backup, you can effectively decrease the carbon footprint within your data centers, and attain your sustainability objectives.

Keystone STaaS, as a part of the SLA, ensures accurate assessment of your sustainability score by providing guaranteed measurements of the sustainability parameters in your storage systems. Factors, such as power efficiency, storage efficiency, and ambient temperature are considered. Power consumption is measured as actual watts per tebibyte (W/TiB) in your Flash storage systems. If there is a violation of the SLA, you are notified through alerts.

[NOTE]
This service is available only for ONTAP Flash platforms, that is on NetApp AFF all-flash storage systems.

Sustainability SLA ensures the following:

* Delivering a guaranteed measurement of maximum number of actual watts per tebibyte (W/TiB) for storage services based on Flash systems for the Extreme, Premium, and Performance service levels.
* Payment of service credit for the missed sustenance guarantees during a billing period, for all eligible subscriptions.

Sustainability builds upon the storage efficiency features of ONTAP, and is applicable for both file and block services. For more information about ONTAP storage efficiency settings, see the concepts under https://docs.netapp.com/us-en/ontap/concepts/thin-provisioning-concept.html[Storage efficiency] and https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_admin_storage_efficiencies.html#about-storage-efficiencies[ONTAP storage efficiencies].

== Are my subscriptions eligible for sustainability SLA?
Your Keystone STaaS subscriptions are eligible for sustainability SLAs if they fulfil these criteria:

* You have NetApp AFF all-flash storage platform, for example, NetApp AFF A900 or AFF A800 all-flash storage system. For information, see (https://www.netapp.com/data-storage/aff-a-series[AFF A-Series]).
* Your environment consists of a two-node cluster. MetroCluster configurations are not supported.
* AutoSupport has been enabled in your environment. For information, see https://docs.netapp.com/us-en/active-iq/concept_autosupport.html[AutoSupport].
* Your subscriptions consists of only one service level (Extreme, Premium, or Performance). Also, the minimum capacity in the service level definition should be met. For more clarity, see the next section *_How is sustainability measured_*.
* The arrear payment schedule for your subscription is monthly.
* There is no customizations on your subscriptions. Your subscriptions become ineligible for sustainability SLA if there are customizations, such as those pertaining to burst capacity sizing or co-mingling. 

== How is sustainability measured?
The sustainability score for a specific billing period reports the maximum number of actual watts per tebibyte (TiB) for the service levels in your subscriptions.

The following sustainability settings are taken into consideration: 

* Watts: Measures the power usage gathered from daily AutoSupport reports. This includes the power usage in both the controller and attached disk shelves, that is the daily consumption measured from the controller and the weekly consumption measured from the disk shelves
* TiB: It is the maximum of the:
** the sum of the committed capacity and allocated burst capacity for the service level
** effective capacity that is a minimum of 2:1 ratio of the deployed hardware
* Service levels: Extreme, Premium, and Performance

[NOTE]
--
Keystone SLA considers the following range when calculating the sustainability score:

* When reading the power consumption, the ambient temperature should be between 25 and 27 degrees of Celsius. For information, see https://docs.netapp.com/us-en/ontap-cli-9131//storage-shelf-show.html[storage shelf show].
* The storage efficiency ratio should be at least 2:1. For information, https://docs.netapp.com/us-en/ontap-cli-9131//storage-aggregate-show-efficiency.html[storage aggregate show-efficiency].
--

Sustainability SLA guarantees the following metrics: 

|===
|*Service level* | *SLA criteria* |*Minimum committed capacity* |*Platform*
a|
Extreme |<=8 watts/TiB |200 TiB |AFF A800 and AFF A900
a|
Premium |<=4 watts/TiB |300 TiB |AFF A800 and AFF A900 
a|
Performance |<=4 watts/TiB |300 TiB |AFF A800 and AFF A900 

|===


== How can I see my sustainability reports?
The SLA tab on the Active IQ Digital Advisor (Digital Advisor) Keystone dashboard provides a details view of the sustainability score with respect to your Keystone subscriptions. You can access the matrix and generate reports for future analysis and actions.

For more information about Keystone dashboard and reporting, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting].

== What do I do if my sustainability score exceeds the SLA criteria?

You receive alerts when SLA obligations are not met. Any deviation from the criteria defined in your SLA is considered a departure from the sustenance guarantee. If the watts/TiB consumption reported for a billing period exceeds or fails to meet the criteria specified in the SLA, contact and inform NetApp Global Services Support Center (GSSC). For information, see link:../concepts/gssc.html[NetApp Global Services Support Center].