---
sidebar: sidebar
permalink: concepts/sla-sustainability.html
keywords: sustainability, sla, service level agreement, 
summary: sustainability, sla, service level agreement
---

= Sustainability SLA for Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Sustainability, in Keystone STaaS, enables you to achieve sustainable operations in Keystone services. It provides you with insights to environmental sustainability of your storage assets supported by Keystone services. You can evaluate and manage the power consumption and carbon and heat emissions based on the reported metrics.

Sustainability in Keystone STaaS builds on the storage efficiency features of ONTAP and is applicable for both file and block services. For more information, see the concepts under https://docs.netapp.com/us-en/ontap/concepts/thin-provisioning-concept.html[Storage efficiency] and https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_admin_storage_efficiencies.html#about-storage-efficiencies[ONTAP storage efficiencies].

Sustainability guarantees the maximum number of actual watts per tebibyte (TiB) for each service level deployed using ONTAP Flash platforms. It comprises service level agreements (SLAs) for your subscriptions that include the following:

* Delivering a guaranteed measurement of maximum number of actual watts per tebibyte (W/TiB) for Storage services based on Flash systems for the Extreme, Premium, and Performance service levels.
* Payment of service credit for the missed sustenance guarantees during a billing period, for all eligible subscriptions.

== Is my subscription eligible for sustainability SLA?
Your Keystone STaaS subscriptions are eligible for sustainability SLAs if they fulfil these criteria:

* Your hardware belongs to NetApp AFF all-flash storage system (https://www.netapp.com/data-storage/aff-a-series[AFF A-Series]).
* In your environment, there is a setup consisting of a two-node cluster. MetroCluster configurations are not supported.
* AutoSupport has been enabled in your environment. For information, see https://docs.netapp.com/us-en/active-iq/concept_autosupport.html[AutoSupport].
* Your subscriptions is assigned only one service level (Extreme, Premium, or Performance). Also, the minimum capacity in the service level definition should be met.
* The arrear payment schedule for your subscription is monthly.
* If there are any customizations allocated to your subscription, such as pertaining to burst capacity sizing or co-mingling, your subscription is not eligible for sustainability SLA. 
* The storage efficiency ratio should be at least 2:1. For information, https://docs.netapp.com/us-en/ontap-cli-9131//storage-aggregate-show-efficiency.html[storage aggregate show-efficiency].
* When reading the power consumption, the ambient temperature is between 25 and 27 degrees of Celsius. For information, see https://docs.netapp.com/us-en/ontap-cli-9131//storage-shelf-show.html[storage shelf show].



For more information about Keystone dashboard and reporting, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting].


