---
sidebar: sidebar
permalink: concepts/supported-storage-services.html
keywords: storage service, service definition, keystone STaaS storage service,
summary: Supported storage services
---

= Supported storage services 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone service supports the base storage types of ONTAP, file and block. It also supports object storage for StorageGRID platform and data management capabilities for Cloud Volumes ONTAP.

For information about Service Levels, see link:../concepts/service-levels.html[Service Levels in Keystone].

== Base storage services
The base storage services for file and block offer default data protection services by leveraging NetApp technologies, such as SnapMirror, SnapVault, and Snapshot. Data tiering to NetApp storage target is also included by default in file and block storage service tiers. You can additionally opt for add-on services for data protection and tiering. For information about add-on services, see link:../concepts/adp.html[Advanced data protection] and link:../concepts/data-tiering.html[Data tiering].
|===
a| Storage service |Platform |Protocols |Supported features

a| File storage
a|ONTAP
a|FC and iSCSI
a|Supported ONTAP features:

FlexVol
FlexGroup
Snapshot copies
SnapMirror (Asynchronous)
SnapVault
SnapLock Enterprise
FabricPool/Cloud tiering
SnapRestore
FlexClone
SnapCenter (license is included but is not a part of Keystone services, and management is not guaranteed)
a| Block storage
a|ONTAP
a|NFS and CIFS
a|Supported ONTAP features:

FlexVol
FlexGroup
Snapshot copies
SnapMirror (Asynchronous)
SnapVault
SnapLock Enterprise
FabricPool/Cloud tiering
SnapRestore
FlexClone
SnapCenter (license is included but is not a part of Keystone services, and management is not guaranteed)

a| Object storage
a|StorageGRID
a|S3
a|Supports multiple information lifecycle management (ILM) policies across multiple sites.
Note:
Each site requires a separate subscription.


|===

== Cloud storage services
Keystone STaaS supports Cloud Volumes ONTAP data management capabilities on Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform. This service can co-term with your existing subscriptions. The cloud service can be included at any point during the service term. However, if you do not plan to renew your subscription, you cannot include the cloud service during the last 90 days of your subscription.

[NOTE]
Hyperscalar-based compute, storage, and network services required by Cloud Volumes ONTAP are not provided by NetApp as a part of Keystone STaaS subscriptions; they need to be procured directly from hyperscalar cloud service providers.
