---
sidebar: sidebar
permalink: concepts/support-services.html
keywords:  Keystone support, service request, support ticket
summary: If you need help, contact the NetApp Keystone support team.
---

= Get help with Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Keystone support team and Keystone Success Manager (KSM) are responsible for providing you service for your Keystone subscriptions. If you need help, you can contact the Keystone support team.

== NetApp Keystone support
NetApp provides operational services remotely to NetApp Keystone customers. These services encompass a range of operational disciplines across storage management activities. These services include asset and configuration management, capacity and performance management, change management, event, incident and problem management, service request fulfillment, and reporting. NetApp demonstrates a state of control and supporting evidence as required.

== Additional information 
NetApp uses ITOM monitoring solution to proactively monitor and connect to the NetApp Keystone environment for troubleshooting. 

[NOTE]
In a partner-operated model, the tenant and subtenant's service requests are assigned to the partner's service desk. The partner's support tool might have integration with ITOM solution.

For more information about Keystone services, see:

* NetApp Keystone
 https://www.netapp.com/us/solutions/keystone/index.aspx[https://www.netapp.com/us/solutions/keystone/index.aspx^]
* NetApp Product Documentation
 https://docs.netapp.com[https://docs.netapp.com^]

== Keystone support monitoring
NetApp Keystone support monitors the health of your products and subscribed services, provides remote support, and collaborates with your Keystone Success Manager.

.Keystone Success Manager
The Keystone Success Manager (KSM) works closely with you on your Keystone services and updates you on weekly or monthly billing and operational reports. The responsibilities are specified in your NetApp Keystone agreement.

== Generating service requests
During onboarding, if you were provided credentials for accessing and using Netapp Keystone ServiceNow, you can use the portal to generate service requests for issues related to your Keystone subscriptions: 

https://netappkeystone.service-now.com/csm[^]

Ensure that you have the system details, logs, and related information ready before raising the service request. When you raise a service request, the Keystone support team receives the support ticket and accesses the information for troubleshooting. You can follow your ServiceNow ticket to know the status and resolution.

For information about adding support bundles, see link:../installation/monitor-health.html[Generate and collect support bundle].

If you have an open case/ticket that needs to be escalated, send an email to one of the following addresses:
keystone.services@netapp.com
keystone.escalations@netapp.com