---
sidebar: sidebar
permalink: concepts/supported-storage-services.html
keywords: storage service, service definition, keystone STaaS storage service,
summary: Supported storage services
---

= Supported storage services 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Keystone service supports the base storage types of ONTAP, file and block. It also supports object storage for StorageGRID platform and data management capabilities for Cloud Volumes ONTAP.

For information about Service Levels, see link:../concepts/service-levels.html[Service Levels in Keystone].

== Base storage services
The base storage services of Keystone offer data protection services by leveraging NetApp technologies, such as SnapMirror, SnapVault, and Snapshot, and tiering capabilities on supported NetApp storage targets for file and block storage services. You can additionally opt for add-on services for data protection and tiering. For information about add-on services, see link:../concepts/adp.html[Advanced data protection] and link:../concepts/data-tiering.html[Data tiering].
|===
a| Storage service |Basis |Supported features | Protocols

a| File storage
|Based on ONTAP technology
|Supported ONTAP features:

FlexVol
FlexGroup
Snapshot copies
SnapMirror (Asynchronous)
SnapVault
SnapLock Enterprise
FabricPool/Cloud tiering
Restore
Clone
SnapCenter (the license is included but this is not a part of Keystone services and no guaranteed management is provided)
|NFS, CIFS.
a| Block storage
|Based on ONTAP technology
|Supported ONTAP features:

FlexVol
FlexGroup
Snapshot copies
SnapMirror (Asynchronous)
SnapVault
SnapLock Enterprise
FabricPool/Cloud tiering
Restore
Clone
SnapCenter (the license is included but this is not a part of Keystone services and no guaranteed management is provided)
|FC and iSCSI
a| Object storage
|Based on the StorageGRID platform
|Supports multiple information lifecycle management (ILM) policies across multiple sites.
Note:
Each site should have a separate subscription.
|S3

|===

[NOTE]
Data tiering to NetApp storage target is included by default in file and block storage service tiers.

For more information on data tiering, see link:../concepts/data-tiering.html[Data Tiering].
For information about data protection services, see link:../concepts/adp.html[Advanced Data Protection].

== Cloud storage services
Keystone supports Data management capabilities for Cloud Volumes ONTAP on Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform. This service can co-term with your existing subscriptions. The cloud service can be included at any point during the service term. However, if you do not plan to renew your subscription, you cannot include the cloud service during the last 90 days of your subscription.

[NOTE]
Hyperscalar-based compute and storage infrastructure are not provided by NetApp as a part of your Keystone subscriptions; you need to procure them from a hyperscalar cloud service provider.
