---
sidebar: sidebar
permalink: concepts/supported-storage-services-v2.html
keywords: storage, service, service definition, keystone STaaS services,
summary: Keystone STaaS services supports ONTAP and StorageGRID.
---

= Supported storage in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
##Keystone STaaS services for version 2 (v2) support file and block storage of ONTAP, object storage of StorageGRID platform, and Cloud Volumes ONTAP.##

Keystone STaaS provides standard and optional services for your storage. 

*Keystone STaaS standard services*: Standard services are included within the base subscription and are not charged separately.

*Keystone STaaS add-on services*: These are optional, chargeable services that provide additional utilities and benefits on top of standard Keystone STaaS subscription services.

Keystone STaaS services can coexist with each other. For example, a cloud storage subscription can co-term with file, block, and object storage subscriptions. A cloud service can be included at any point during the service term of an existing storage subscription. However, if you do not plan to renew an existing file, block, and object subscription, a cloud storage subscription cannot be added during the last 90 days of the subscription.

== Services for file, block, and object storage
Keystone STaaS services for ONTAP file and block storage, and StorageGRID object storage, support multiple features and protocols, and described in the following table:

|===
a| Storage |Platform |Protocols |Supported features

a| File storage
a|ONTAP
a|NFS and CIFS
a|Supported ONTAP features:

* FlexVol
* FlexGroup
* Snapshot copies
* SnapMirror (Asynchronous)
* SnapVault
* SnapLock Enterprise
* FabricPool/Cloud tiering
* SnapRestore
* FlexClone
* SnapCenter (license is included but is not a part of Keystone services, and management is not guaranteed)
* Autonomous ransomware protection^1^
a|Block storage
a|ONTAP
a|FC and iSCSI 
a|Supported ONTAP features:

* FlexVol
* FlexGroup
* Snapshot copies
* SnapMirror (Asynchronous)
* SnapVault
* SnapLock Enterprise
* FabricPool/Cloud tiering
* SnapRestore
* FlexClone
* SnapCenter (license is included but is not a part of Keystone services, and management is not guaranteed)

a| Object storage
a|StorageGRID
a|S3
a|Supports multiple information lifecycle management (ILM) policies across multiple sites^2^

|===

[NOTE]
^1^ For information about ransomware protection in ONTAP, see https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Autonomous Ransomware Protection^].
^2^ Each site requires a separate subscription.

== Services for cloud storage
Keystone STaaS provides cloud storage services. Keystone STaaS supports Cloud Volumes ONTAP data management capabilities on Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform. 

[NOTE]
Hyperscalar-based compute, storage, and network services required by Cloud Volumes ONTAP are not provided by NetApp as a part of Keystone STaaS subscriptions; these subscriptions need to be procured directly from hyperscalar cloud service providers.