---
sidebar: sidebar
permalink: concepts/support-services.html
keywords:  Keystone support, service request, support ticket
summary: Use the NetApp Support Site to create a support case or find contact information for your Keystone subscriptions.
---

= Get help with Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp provides Keystone customers with operational services. Customers receive a dedicated Keystone Success Manager (KSM), direct support contact options, and proactive monitoring through the ITOM solution.

== NetApp support services
NetApp provides operational services remotely to Keystone customers. These services span a range of storage management activities, including asset and configuration management, capacity and performance management, change management, event and incident management, service request fulfillment, and reporting.

.Keystone Success Manager
Your KSM works closely with you on your Keystone services and provides weekly or monthly billing and operational reports. Specific responsibilities are defined in your NetApp Keystone agreement.

== Contact support
If you experience an issue with your Keystone subscription, log in to the link:https://support.netapp.com[NetApp Support Site^] using your NSS credentials to create a support case.

If you do not have an NSS login, link:https://mysupport.netapp.com/site/user/registration[register your account^] using the serial number (SN) of one of the nodes in your subscription.

For step-by-step instructions with screenshots, see link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case[How to open a technical support case^].

If you prefer to speak with a support representative directly, call one of the following numbers:

* US / Canada: 888 463 8277
* Europe: 00 800 44 638277
* India: 000 800 100 8948
* More global numbers: link:https://www.netapp.com/company/contact-us/support/[https://www.netapp.com/company/contact-us/support/^]

== Support monitoring
NetApp uses the ITOM monitoring solution to proactively monitor the health of your products and subscribed services and connect to the NetApp Keystone environment for troubleshooting.

== Additional resources
For more information about Keystone services, see:

* link:https://www.netapp.com/us/solutions/keystone/index.aspx[NetApp Keystone^]
* link:https://docs.netapp.com[NetApp Product Documentation^]

*Related information*

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform[How to Identify Serial Number of ONTAP Platform^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case[Which serial number to use when creating StorageGRID technical support case^]
