---
sidebar: sidebar
permalink: concepts/supported-storage-capacity.html
keywords: storage capacity, capacity definition, keystone STaaS storage capacity,
summary: Supported storage capacities
---

= Supported storage capacities in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Keystone service capacities include:

== Logical capacity
This is the data placed into the Keystone infrastructure by a customer. All Keystone capacities refer to a logical capacity.
For example, if a 1 TiB file is stored on the Keystone infrastructure, then at least 1 TiB of capacity must be purchased.

== Committed capacity
The minimum logical capacity billed each month for the duration of the term:

** Capacity is committed to each service level.
** Committed capacity and additional service levels can be added during the term.

=== Changes to committed capacity
During the tenure of a subscription, you can change the committed capacities. However, there are certain preconditions:

*	The committed capacity can be decreased based on certain conditions. For information, see ...
*	The committed capacity cannot be increased 90 days prior to the expiry of your subscription, unless the subscription is to be renewed for an additional 12 month term.
* You can request changes to committed capacity through the Cloud Manager interface or through Keystone Success Manager.
For information about requesting changes, see ....

== Consumed capacity
Consumed capacity refers to the capacity in TiB of storage currently being consumed on the service. Keystone service considers the sum of the logical used sizes (not the physical capacity used) of all volumes on a particular service level to be considered as consumed capacity for that service level.

== Burst capacity
This is the consumed capacity that has exceeded the committed capacity. Note the following points:

** Keystone service provides 20% capacity in excess of the committed capacity.
** Burst capacity can be consumed on an elastic basis and is charged on a daily basis of the consumed average.
** Burst capacity up to 20% is charged at a same rate as the committed capacity.

== Billed capacity
Monthly bill = (committed capacity [TiB] * committed rate [$/TiB]) + (daily average provisioned burst capacity [TiB] * burst rate [$/TiB]). The monthly bill contains a minimum charge based on the committed capacity.

The monthly bill varies beyond the minimum charge based on daily average burst capacity consumption.
