---
sidebar: sidebar
permalink: concepts/supported-storage-capacity.html
keywords: storage capacity, capacity definition, keystone STaaS storage capacity,
summary: Learn about the types of storage capacities supported by the NetApp Keystone STaaS service.
---

= Supported storage capacities in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The NetApp Keystone STaaS service supports several types of storage capacities. Understanding these different capacity terms can help as you use Keystone.

== Logical capacity
This is the data placed on the Keystone infrastructure by a customer. All Keystone capacities refer to a logical capacity.
For example, if a 1 TiB file is stored on the Keystone infrastructure then a minimum of 1 TiB of capacity should be purchased.

== Committed capacity
The minimum logical capacity billed each month during the subscription:

** Capacity is committed to each service level.
** Committed capacity and additional service levels can be added during the term.

=== Changes to committed capacity
During the tenure of a subscription, you can change the committed capacities. However, there are certain preconditions:

*	The committed capacity can be decreased based on certain conditions. For information, see link:../concepts/capacity-requirements.html[Capacity reduction].
*	The committed capacity cannot be increased 90 days prior to the expiry of your subscription, unless the subscription is to be renewed for an additional 12-month term.
* You can request changes to committed capacity through the BlueXP interface or through Keystone Success Manager (KSM).
For information about requesting changes, see link:../concepts/gssc.html[NetApp Keystone support].

== Consumed capacity
##Consumed capacity refers to the capacity (in TiB of storage) currently being consumed on the service. It is the sum of:##

* ##The logical capacity used to store all instances and types of user data (like copies, mirrored copies, and versions).##
* ##The logical capacity used to store clone volumes that are more than 10% of the size of the original volume.##
* ##The physical capacity used to store the differential data from Snapshot copies.##
* ##The allocated physical capacity.##

== Burst capacity
Keystone service enables you to use additional capacity on top of the committed capacity for a service level. This is the burst capacity usage. Note these points:

** Burst capacity is agreed upon in the Keystone agreement. It is usually set up to 20% above the committed capacity, and is charged at the same rate as the committed capacity.
** Burst capacity can be consumed on an elastic basis and is charged on a daily basis for the consumed average.

== Billed capacity
Monthly bill = (committed capacity [TiB] * committed rate [$/TiB]) + (daily average provisioned burst capacity [TiB] * burst rate [$/TiB]). The monthly bill contains a minimum charge based on the committed capacity.

The monthly bill varies beyond the minimum charge based on daily average burst capacity consumption.
