---
sidebar: sidebar
permalink: concepts/supported-storage-services.html
keywords: storage, service, service definition, keystone STaaS services,
summary: Keystone STaaS services supports ONTAP and StorageGRID.
---

= Supported storage in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
##Keystone STaaS supports unified, block-optimized, AFX, and object storage on NetApp platforms, as well as Cloud Volumes ONTAP. Each storage type is defined as a data storage type (DST) and is available with standard services included in the base subscription, along with optional add-on services.##

== Keystone STaaS standard and add-on services

Keystone STaaS provides standard and optional services for your storage. 

*Keystone STaaS standard services*: Standard services are included within the base subscription and are not charged separately.

*Keystone STaaS add-on services*: These are optional, chargeable services that provide additional utilities and benefits on top of standard Keystone STaaS subscription services.

##<must review>##
##You can subscribe to multiple Keystone STaaS services at the same time. When cloud services are added to a subscription, they share the same term as unified, block-optimized, and/or object storage. A cloud service can be added at any point during an active storage subscription. However, if you do not plan to renew an existing unified, block-optimized, or object storage subscription, a cloud service cannot be added during the last 90 days of that subscription.##

NOTE: ##An AFX subscription is standalone and cannot be combined with unified, block-optimized, or object storage in the same subscription. If you need AFX alongside other storage types, you must order them as separate subscriptions.##

== ##<must review>##Supported data storage types
Keystone STaaS services for unified, block-optimized, object, and AFX storage, support multiple features and protocols, and described in the following table:

|===
a|Data storage type |Description| Platform |Protocols |Supported features

a|Unified 
a|Includes file, block, and S3 object storage
a|ONTAP on AFF and FAS systems
a|FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3
a|Supports all ONTAP One features
a|Block-optimized
a|Includes block storage
a|NVMe/TCP, NVMe/FC, FC, iSCSI
a|FC and iSCSI 
a|Supports all ONTAP One for SAN features
a|AFX
a|Includes file and block storage on a disaggregated storage platform
a|ONTAP on AFX systems
a|NFSv3, NFSv4/RDMA, pNFS, SMB, S3
a|Supports all ONTAP One features
a|Object
a|Includes object storage 
a|StorageGRID
a|S3
a|Supports all StorageGRID features


|===

To learn more about ONTAP One, refer to link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[ONTAP licensing overview^] and link:https://www.netapp.com/blog/ontap-one/[ONTAP One: The full power of ONTAP, now all in one^].

== Services for cloud storage
Keystone STaaS provides cloud storage services. Keystone STaaS supports Cloud Volumes ONTAP data management capabilities on Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform. 

[NOTE]
Hyperscaler-based compute, storage, and network services required by Cloud Volumes ONTAP are not provided by NetApp as a part of Keystone STaaS subscriptions; these subscriptions need to be procured directly from hyperscaler cloud service providers.