---
sidebar: sidebar
permalink: concepts/data-tiering.html
keywords: add-on services, add-on, data tiering
summary: Add-on, additional Services Details, data tiering
---

= Data tiering
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Keystone (Keystone) service includes a tiering capability with your subscribed file and block services that identifies less-frequently used data and tiers it to a cold storage that is owned, deployed, and managed by NetApp.

You can subscribe to this add-on services as a part of your Keystone subscription.
For information about the base storage and cloud storage service, see link:../concepts/supported-storage-services.html[Supported storage services]

For information about Service Levels, see link:../concepts/service-levels.html[Service Levels in Keystone]

[NOTE]
Data tiering to NetApp storage target is included by default in file and block storage service tiers. The add-on service is required only when data is tiered any non-NetApp storage, such as AWS S3, Azure Blob, and EMC ECS.

The tiering capability leverages the NetApp FabricPool technology that enables automated tiering of data to low-cost object storage tiers either on or off premises. With this capability, infrequently accessed data is automatically tiered to a lower cost storage either on premises or in the cloud, based on the services agreed upon.

The tiering service enables tiering from Extreme, Premium, Performance, Standard, and Value tier to Object target. The hot tier and cold tier are metered and invoiced separately. Data tiering can be added any time, without change in pricing and adds more flexibility in terms of hot:cold ratio.

Go through the following calculations for understanding this better:

If the target for cold storage tier is:

*	Value tier (up to 500TiB), Object Tier (>500TiB), existing SGWS grid (customer owned) – There is no additional charge, and it is part of basic storage service.
*	Public cloud (AWS, Azure, Google) and any other third-party supported object storage – There is an additional charge for data capacity that is committed as a tier out charge.

The charges involved in the add-on tiering subscription is not a one-time charge and you need to pay for it for the entire term to sustain the tiering relationship between Keystone on-premises file and block services and the third-party supported object storage target.

This offering only provides the capability to tier cold data to cheaper target storage, not the public cloud/hyperscalar infrastructure costs.
[NOTE]
Hyperscalar-based compute and storage infrastructure are not provided by NetApp as a part of your Keystone subscriptions, and you need to procure them from a hyperscalar cloud service provider.
