---
sidebar: sidebar
permalink: concepts/usps.html
keywords: netapp, keystone, US citizen support, USPS, Keystone Success Manager, USPS support
summary: "United States Protected Support is an add-on service that provides delivery and support of ongoing Keystone services from U.S. citizens on U.S. soil."
---

= USPS add-on for Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
United States Protected Support (USPS) is an add-on offering for NetApp Keystone Subscriptions. It entitles you to receive delivery and support of ongoing Keystone services from U.S. citizens on U.S. soil.

Read the following sections to understand which elements of your subscriptions are bound by this add-on service and are provided under the terms of NetApp Keystone Agreement.footnote:disclaimer1[The services and offerings described here are subject to, and limited and governed by a fully-executed Keystone Agreement.]

== NetApp USPS monitoring
NetApp USPS Keystone support team monitors the health of your products and subscribed services, provides remote support, and collaborates with your Keystone Success Manager. All personnel monitoring the products associated with the relevant Keystone subscription orders are U.S citizens operating on U.S. soil.

== Keystone Success Manager
The Keystone Success Manager (KSM) is a U.S. citizen operating on U.S. soil. Their responsibilities are specified in your NetApp Keystone Agreement.

== Deployment activities
Where available, onsite and remote deployment and installation activities are conducted by U.S. citizens on U.S. soil. footnote:disclaimer[Availability of appropriate personnel for onsite activities is dependent on the geographical location at which the Keystone systems are deployed.]

== Support
Where available, the necessary onsite troubleshooting and support activities are conducted by U.S. citizens on U.S. soil. footnote:disclaimer[]
