---
sidebar: sidebar
permalink: installation/asup-config.html
keywords: ASUP, AutoSupport configuration
summary: procedure for configuring AutoSupport for Keystone
---

= Configure AutoSupport collector for Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The function of the AutoSupport collector service is to retrieve Keystone data and send the data for accurate billing. If you are using the AutoSupport collector service, you need to configure the AutoSupport telemetry mechanism to include specific Keystone data in the daily support bundles sent by the ONTAP clusters.

For information about managing AutoSupport services by using ONTAP CLI, see https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html[Manage AutoSupport overview^].

.Prerequisites

To ensure precise data collection for Keystone billing, it is essential to incorporate the following subsystems into the the AutoSupport collector. For information about AutoSupport subsystems, see https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html[What AutoSupport subsystems are^].

|===
|Subsystem name |Data item required for Keystone billing

a| wafl | `VOLUME-CLONE-SHOW.XML`
a| performance | `QOS-POLICY-GROUP.XML` and `QOS-ADAPTIVE-POLICY.XML`
a| snapshot | `SNAPSHOT.XML`
a| platform | `ENVIRONMENT.txt`

|===

These subsystems are included by default in the weekly bundles, where the `asup_type` is `DOT-REGULAR`, and the `asup_subject` is `HA Group Notification (WEEKLY_LOG) NOTICE`. However, you need to add them to daily bundles for retrieving and reporting Keystone usage data. Follow these steps:

.Steps

* As a system administrator user, log in to the Keystone ONTAP cluster by using SSH. For information, see https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html[Access the cluster by using SSH^].
* Run the following command and verify the existing configuration:
====
autosupport trigger show -node * -autosupport-message management.log -instance
====

For more information about this command, see https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-manifest-show.html#parameters[system node autosupport manifest show^].

* Modify the daily log content by running this command:
====
autosupport trigger modify -node * -autosupport-message management.log -basic-additional <existing comma-separated subsystems>, <new subsystems>
====
For more information about these commands, see https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html[system node autosupport trigger modify^].



