---
sidebar: sidebar
permalink: installation/linux-installation.html
keywords: Linux installation Keystone, Linux Collector installation
summary: Install the Keystone Collector software from the YUM software repository.
---

= Install Keystone Collector on Linux systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can install the Keystone Collector software on a Linux server using an RPM or a Debian package. Follow the installation steps depending on your Linux distribution.

[role="tabbed-block"]
====

.Using RPM
--
. SSH to the Keystone Collector server and elevate to `root` privilege.
. Import the Keystone public signing signature: 
`# rpm --import https://keystone.netapp.com/repo/RPM-GPG-NetApp-Keystone-20221101`
. Ensure that the correct public certificate has been imported by checking the fingerprint for Keystone Billing Platform in the RPM database: 
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint`
The correct fingerprint looks like this:
`90B3 83AF E07B 658A 6058 5B4E 76C2 45E4 33B6 C17D`
. Download the `keystonerepo.rpm` file:
`curl -O https://keystone.netapp.com/repo/keystonerepo.rpm`
. Verify the authenticity of the file:
`rpm --checksig -v keystonerepo.rpm`
A signature for an authentic file looks like this:
`Header V4 RSA/SHA512 Signature, key ID 33b6c17d: OK`
. Install the YUM software repository file:
`# yum install keystonerepo.rpm`
. When the Keystone repo is installed, install the keystone-collector package through the YUM package manager:
`# yum install keystone-collector`
--

.Using Debian
--
. SSH to the Keystone Collector server and elevate to `root` privilege.
`sudo su`
. Download the `keystone-sw-repo.deb` file:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Install the Keystone software repository file:
`# dpkg -i keystone-sw-repo.deb`
. Update the package list:
`# apt-get update`
. When the Keystone repo is installed, install the keystone-collector package:
`# apt-get install keystone-collector`
--

====


[NOTE]
On completing the installation, you can use the Keystone Collector Management Terminal User Interface (TUI) utility to perform the configuration and monitoring activities. You can use various keyboard controls, such as the Enter and arrow keys, to select the options and navigate across this TUI. See link:../installation/configuration.html[Configure Keystone Collector] and link:../installation/monitor-health.html[Monitor system health] for information.
