---
sidebar: sidebar
permalink: installation/linux-installation.html
keywords: Linux installation Keystone, Linux Collector installation
summary: installing Keystone collector on Linux
---

= Installing Keystone Collector on Linux systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The Keystone Collector software is distributed by an online YUM software repository. You need to import and install the file on a Linux server. 

Follow these steps to install the software on your Linux server:

. SSH to the Keystone Collector server and elevate to `root` privilege.
. Import the Keystone public signing signature: 
`# rpm --import https://keystone.netapp.com/repo/RPM-GPG-NetApp-Keystone-20221101`
. Ensure that the correct public certificate has been imported by checking the fingerprint for Keystone Billing Platform in the RPM database: 
`# rpm -qa gpg-pubkey --qf '%_<Description>_'|gpg --show-keys --fingerprint`
The correct fingerprint looks like this:
`90B3 83AF E07B 658A 6058  5B4E 76C2 45E4 33B6 C17D`
. Download the `keystonerepo.rpm` file:
`curl -O https://keystone.netapp.com/repo/keystonerepo.rpm`
. Verify the authenticity of the file:
`rpm --checksig -v keystonerepo.rpm`
A signature for an authentic file looks like this:
`Header V4 RSA/SHA512 Signature, key ID 33b6c17d: OK`
. Install the YUM software repository file:
`# yum install keystonerepo.rpm`
. When the Keystone repo is installed, install the keystone-collector package through the YUM package manager:
`# yum install keystone-collector`

[NOTE]
On completing the installation, you can use the Keystone Collector Management Terminal User Interface (TUI) utility to perform the configuration and monitoring activities. You can use various keyboard controls, such as the Enter and arrow keys, to select the options and navigate across this TUI. See link:../installation/configuration.html[Configure Keystone Collector] and link:../installation/monitor-health.html[Monitor system health] for information.
