---
sidebar: sidebar
permalink: dark-sites/requirements.html
keywords: installation, private mode, requirement, vmware vsphere, linux, networking,disk, space
summary: Before installing Keystone Collector in an environment without internet access, also known as a _dark site_ or _private mode_, ensure your systems are prepared with the necessary software and meet all required prerequisites.
---

= Prepare for installation in private mode
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before installing Keystone Collector in an environment without internet access, also known as a _dark site_ or _private mode_, ensure your systems are prepared with the necessary software and meet all required prerequisites. 

== Requirements for VMware vSphere

* ESXI 6.5 or later
* VMware vCenter Server
* Core: 1 CPU
* RAM: 2 GB
* Minimum Disk space: 20 GB vDisk

== Requirements for Linux

* Operating system: Debian v12 or Red Hat Enterprise Linux 8.6+
* Core: 2 CPU
* RAM: 4 GB
* Minimum Disk space: 50 GB vDisk
** At least 2 GB free in `/var/lib/`
** At least 48 GB free in `/opt/netapp`

For customer provided Linix server, it should also have the following third-party packages installed or if available via repo will be installed automatically as pre-requisites:

* RHEL8
** python3 >= v3.6.8, python3 <= v3.9.13
** https://access.redhat.com/downloads/content/podman/x86_64/package-latest[podman]
** sos
** yum-utils
** python3-dnf-plugin-versionlock
* Debian v12
** python3 >= v3.9.0, python3 <= v3.12.0
** podman
** sosreport


== Networking requirements

The networking requirements of Keystone Collector are listed below.

* Active IQ Unified Manager (Unified Manager) 9.10 or later, configured on a sever with the API Gateway functionality enabled.
* The server should be accessible by the Keystone Collector server on port 443 (HTTPS).
* A service account for Keystone Collector on the Unified Manager server with Application User permissions enabled.
* No external internet connectivity required.
* Once a month file to be exported from Collector and transferred via operator email to Keystone Staff.



