---
sidebar: sidebar
permalink: dark-sites/requirements.html
keywords: installation, private mode, requirement, vmware vsphere, linux, networking,disk, space
summary: Before installing Keystone Collector in an environment without internet access, also known as a _dark site_ or _private mode_, ensure your systems are prepared with the necessary software and meet all required prerequisites.
---

= Prepare for installation in private mode
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before installing Keystone Collector in an environment without internet access, also known as a _dark site_ or _private mode_, ensure your systems are prepared with the necessary software and meet all required prerequisites. 

== Requirements for VMware vSphere

* Operating system: VMware vCenter server and ESXi 6.7 or later
* Core: 1 CPU
* RAM: 2 GB
* Disk space: 20 GB vDisk

== Requirements for Linux

* Operating system: Debian v12 or Red Hat Enterprise Linux 8.6 or later
* Core: 2 CPU
* RAM: 4 GB
* Disk space: 50 GB vDisk
** At least 2 GB free in `/var/lib/`
** At least 48 GB free in `/opt/netapp`

The same server should also have the following third-party packages installed. If available through the repository, these packages will be automatically installed as prerequisites:

* RHEL8
** python3 >=v3.6.8, python3 \<=v3.9.13
** podman
** sos
** yum-utils
** python3-dnf-plugin-versionlock
* Debian v12
** python3 >= v3.9.0, python3 \<= v3.12.0
** podman
** sosreport


== Networking requirements

The networking requirements for Keystone Collector include the following:

* Active IQ Unified Manager (Unified Manager) 9.10 or later, configured on a sever with the API Gateway functionality enabled.
* The Unified Manager server should be accessible by the Keystone Collector server on port 443 (HTTPS).
* A service account with Application User permissions should be set up for the Keystone Collector on the Unified Manager server.
* External internet connectivity is not required.
* Each month, export a file from Keystone Collector and email it to the NetApp support team. For more information on how to contact the support team, refer to link:../concepts/gssc.html#netapp-global-services-and-support-center[Get help with Keystone].



