---
sidebar: sidebar
permalink: release-notes/fixed-issues.html
keywords: fixed issues
summary: issues fixed in different releases of Keystone STaaS
---

= Fixed issues
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Issues that were found in previous releases of NetApp Keystone STaaS services have been fixed in later releases. These are the fixes.

[cols="3*",options="header"]
|===
|Issue Description |After the fix |Fixed in release

a|No information is available on the *Assets* tab for AutoSupport subscriptions.
a|Fixed
a|March 14, 2024
a|If both MetroCluster and FabricPool were enabled in an environment where rate plans for both tiering and object storage were applicable, the service levels could be incorrectly derived for the mirror volumes (both constituent and FabricPool volumes).
a|Correct service levels are applied to mirror volumes.
a|February 29, 2024
a|For some subscriptions having a single service level or rate plan, the AQoS compliance column was missing in the CSV output of the *Volumes* tab reports.
a|The compliance column is visible in the reports.
a|February 29, 2024
a|In some MetroCluster environments, occasional anomaly was detected in the IOPS density charts in the *Performance* tab. This happened due to inaccurate mapping of volumes to service levels.
a|The charts are correctly displayed.
a|February 29, 2024
a|The usage indicator for a burst consumption record was being displayed in amber.
a|The indicator appears in red.
a|December 13, 2023
a|The date range and data in the Capacity Trend, Current Usage, and Performance tabs were not converted to UTC timezone.
a|The date range for query and data in all the tabs are displayed in UTC time (server timezone). The UTC timezone is also displayed against each date field on the tabs.
a|December 13, 2023
a|There was a mismatch in the start date and end date between the tabs and the downloaded CSV reports.
a|Fixed.
a|December 13, 2023



|===