---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: netapp, keystone, release notes, known issues
summary: known issues in Keystone STaaS
---

= Known issues in Keystone STaaS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known issues identify problems that might prevent you from using Keystone subscription services effectively. 

The following known issues have been reported in NetApp Keystone STaaS.

[cols="3*",options="header"]
|===
|Known issue |Description |Workaround

a|Extended data display for single-day selection in the *Capacity Trends* tab.
a|When the date corresponding to today is selected as both the start and end date for the previous month from the *Capacity Trend* option in the *Capacity Trends* tab, the usage charts display data for a period extending from the selected start date to the current date, instead of showing data for the specified single-day period.
a|None
//NSEKEY-9842
a|Historical accrued burst data not available for service levels.
a|The historical accrued burst usage data for the *CVO Primary* and *CVO Secondary* service levels within the the *Capacity Trend* tab is not available for subscriptions that are not configured with a MetroCluster configuration. 
a|None
//NSEKEY-9855
a|Incorrect display of object storage consumed value for AutoSupport subscriptions.
a|If AutoSupport telemetry is used for gathering Keystone data, the consumed value for object storage listed on the *Volume Details* tab is displayed incorrectly for for subscriptions with file, block, and object services.
a|Refer to the consumed value for object storage mentioned within the *Current Usage* tab for correct information.
//NSEKEY-9265
a|Unable to view cluster-level information within the *Assets* tab.
a|Cluster-level details are not available from the *Assets* for AutoSupport subscriptions that are configured with a MetroCluster configuration. 
a|None

|===


