---
sidebar: sidebar
permalink: release-notes/known-limitations.html
keywords: limitations, known limitations in Keystone STaaS
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by Keystone STaaS services or components, or that do not interoperate correctly. Review these limitations carefully.

== Keystone Collector limitations

=== Keystone Collector cannot start on vSphere 8.0 Update 1 
A Keystone Collector virtual machine (VM) with VMware vSphere version 8.0 Update 1 cannot be switched on, and the following error is displayed:

`Property 'Gateway' must be configured for the VM to power on.`

See Knowledge Base article link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_start_on_vSphere_8.0_U1[Keystone Collector fails to start on vSphere 8.0 U1^] for information and resolution.

=== Issues in support bundle generation on Kerberos
If the Keystone Collector home directory is mounted over NFSv4 using Kerberos, the support bundle is not generated, and the following error message is displayed:

`subprocess.CalledProcessError: Command '['sosreport', '--batch', '-q', '--tmp-dir', '/home/<user>']' returned non-zero exit status 1.`

See Knowledge Base article https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_fails_to_generate_support_bundle_on_Kerberized_home_directory[Keystone Collector fails to generate support bundle on Kerberized home directory^] for information and resolution.

=== Issue for Keystone Collector in communicating within specific network range
Keystone Collector is unable to communicate with devices within the 10.88.0.0/16 network range when the `ks-collector` service is running. See Knowledge Base article link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_container_conflict_with_customer_network[Keystone Collector container conflict with customer network^] for information and resolution.

=== Keystone Collector cannot verify CA certificate when SSL is enabled for MitM attacks
If, in an environment, SSL/TLS inspection is enabled at the border firewall to stop man-in-the-middle (MitM) attacks, Keystone Collector is unable to establish an HTTPS connection because the certificate is not from a trusted certificate authority (CA). See Knowledge Base article link:https://kb.netapp.com/hybrid/Keystone/Collector/Keystone_Collector_cannot_verify_Customer_Root_SSL_CA_certificate[Keystone Collector cannot verify Customer Root SSL CA certificate^] for information and resolution.

