---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: netapp, keystone, release notes, known issues
summary: known issues in Keystone STaaS
---

= Known issues in Keystone STaaS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known issues identify problems that might prevent you from using Keystone subscription services effectively. 

The following known issues have been reported in NetApp Keystone STaaS.

[cols="3*",options="header"]
|===
|Known Issue |Description |Workaround
a|Information on AQoS non-compliant volumes and MetroCluster partners is unavailable for AutoSupport subscriptions.
a|If AutoSupport telemetry is used for gathering Keystone data, the count of AQoS non-compliant volumes listed on the *Volume Summary* and *Current Usage* tabs, and information about MetroCluster partners, are unavailable if Keystone data is not present for 24 hours.
a|None
a|Occasional mismatch in the number of AQoS non-compliant volumes in the *Volumes* tab.
a|If there are two service levels assigned to a volume that fulfils AQoS compliance for only one service level, the number of AQoS non-compliant volumes listed on the *Volume Summary* and *Volume Details* tabs might differ. 
a|None
|===

