---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: netapp, keystone, release notes, known issues
summary: known issues in Keystone STaaS
---

= Known issues in Keystone STaaS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known issues identify problems that might prevent you from using Keystone subscription services effectively. 

The following known issues have been reported in NetApp Keystone STaaS.

[cols="3*",options="header"]
|===
|Known Issue |Description |Workaround
a|Occasional mismatch in the number of AQoS non-compliant volumes in the *Volumes* tab.
a|If there are two service levels assigned to a volume that fulfils AQoS compliance for only one service level, the number of AQoS non-compliant volumes listed on the *Volume Summary* and *Volume Details* tabs might differ. 
a|None
a|*Assets* tab not populated for AutoSupport subscriptions.
a|If AutoSupport telemetry is used for gathering Keystone data for a subscription number, no information is retrieved on the *Assets* tab.
a|None
a|Incorrect appearance of tooltip.
a|The tooltip for the *Current Burst* index icon appears incorrectly in the *Capacity Trend* tab.
a|Refer to the correct tooltip text "_The amount of burst capacity currently being consumed. Note this is for current billing period, not the selected date range._"

|===

