---
sidebar: sidebar
permalink: release-notes/known-issues.html
keywords: netapp, keystone, release notes, known issues
summary: known issues in NetApp Service Engine
---

= Known issues in NetApp Service Engine
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following known issues have been reported in NetApp Keystone STaaS. You might encounter these issues when you provision or use the storage that is managed by your Keystone subscriptions.

[cols="3*",options="header"]
|===
|Known Issue |Description |Workaround
a|Incorrect service level derived for mirror volumes.
a|If both MetroCluster and FabricPool are enabled in an environment where rate plans for both tiering and object storage are applicable, the service levels derived for the mirror volumes (both constituent and FabricPool volumes) might be incorrect.
a|None.
a|Partially visible links and icons in the *Subscriptions* tab.
a|A few links and icons, such as the link to the *Current Usage* tab and the tooltips of some columns are partially visible.
a|No workaround is required. The links work as expected.


|===
