---
sidebar: sidebar
permalink: release-notes/whats-new.html
keywords: new features, release notes, enhancements, what's new
summary: NetApp offers you new and enhanced features in every release of Keystone STaaS services. 
---

= What's new in Keystone STaaS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp offers you new and enhanced features in every release of Keystone STaaS services. 

The following enhancements are introduced in the *Keystone Subscriptions* screen of Active IQ Digital Advisor (also known as Digital Advisor):

== January 08, 2025

=== ##Addition of daily accrued burst data viewing options##
##You can now view daily accrued burst usage data in either graph or table format for a monthly or quarterly billing period by clicking the bar that displays the invoiced data. To learn more, refer to link:../integrations/capacity-trend-tab.html#view-daily-accrued-burst-data[View daily accrued burst data].##
//NSEKEY-11952

== December 12, 2024

=== Renamed Logical Used column
The *Logical Used* column in the *Volume Details* tab within *Volumes & Objects* is now renamed to *Keystone Logical Used*.
//NSEKEY-11787

=== Enhanced Assets tab
The *Assets* tab in the *Keystone Subscriptions* screen now has two new sub-tabs: *ONTAP* and *StorageGRID*. These sub-tabs offer detailed cluster-level insights for ONTAP and grid-level information for StorageGRID based on your subscriptions. To learn more, refer to link:../integrations/assets-tab.html[Assets tab^].
//NSEKEY-11756

=== New Hide/Show Columns option
The *Volume Details* tab within *Volumes & Objects* now includes a *Hide/Show Columns* option. This option enables you to select or deselect columns to customize the tabular listing of volumes according to your preference. To learn more, refer to link:../integrations/volumes-objects-tab.html[Volumes & Objects tab^].
//NSEKEY-12126, NSEKEY-12128

== November 21, 2024

=== Enhanced invoiced accrued burst
You can now view accrued burst usage data on a quarterly basis through the *Invoiced Accrued Burst* option if you have opted for a quarterly billing period. To learn more, refer to link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst[View invoiced accrued burst^].
//NSEKEY-9876

=== New columns in the Volumes Details tab
To improve clarity in calculating logical usage, two new columns have been added to the *Volume Details* tab within the *Volumes & Objects* tab:

* *Logical AFS*: Displays the logical capacity used by the volume’s active file system.
* *Physical Snapshot*: Displays the physical space used by the snapshots.

These columns provide better clarity on the *Logical Used* column, which shows the combined logical capacity used by the volume's active file system and the physical space used by snapshots.
//NSEKEY-10959

== November 11, 2024 

=== Enhanced report generation
You can now generate a consolidated report to view the details of your Keystone data using the Report feature in Digital Advisor. To learn more, refer to link:../integrations/aiq-keystone-details.html#generate-consolidated-report[Generate consolidated report^].
//NSEKEY-5735

== July 10, 2024

=== Label modifications
The label *Current Usage* is changed to *Current Consumption*, and *Capacity Trend* is changed to *Consumption Trend*.

=== Search bar for subscriptions
The *Subscriptions* dropdown across all tabs within the *Keystone Subscriptions* screen now includes a search bar. You can search for specific subscriptions listed in the *Subscriptions* dropdown.
//NSEKEY-9965

== June 27, 2024

=== Consistent display of subscription 
The *Keystone Subscriptions* screen is updated to display the selected subscription number across all tabs.
 
* When any tab within the *Keystone Subscriptions* screen is refreshed, the screen automatically navigates to the *Subscriptions* tab and reset all tabs to the first subscription listed in the *Subscription* dropdown.
* If the selected subscription is not subscribed to performance metrics, the *Performance* tab will display the first subscription listed in the *Subscription* dropdown upon navigation.
//NSEKEY-9820

== May 29, 2024

=== Enhanced Burst indicator 
The *Burst* indicator in the usage graph index is enhanced to display the burst limit percentage value. This value changes depending on the agreed-upon burst limit for a subscription. You can also view the burst limit value in the *Subscriptions* tab by hovering over the *Burst Usage* indicator in the *Usage Status* column.
//NSEKEY-8625

=== Addition of service levels
The service levels *CVO Primary* and *CVO Secondary* are included to support Cloud Volumes ONTAP for subscriptions that has rate plans with zero committed capacity or those configured with a metro cluster.

* You can view the capacity usage graph for these service levels from old dashboard of the *Keystone Subscriptions* widget and the *Capacity Trend* tab, and also detailed usage information from the *Current Usage* tab.
* In the *Subscriptions* tab, these service levels are displayed as `CVO (v2)` in the *Usage Type* column, allowing for the identification of billing according to these service levels.
//NSEKEY-8923

=== Zoom-in feature for short-term bursts
The *Capacity Trend* tab now includes a zoom-in feature to view the details of short-term bursts in the usage charts. For more information, see link:../integrations/capacity-trend-tab.html[Capacity Trend tab^].
//NSEKEY-9459

=== Enhanced display of subscriptions
The default display of subscriptions is enhanced to sort by tracking ID. The subscriptions in the *Subscriptions* tab, including in the *Subscription* dropdown and CSV reports, will now be displayed based on the alphabetical sequence of the tracking IDs, following the order of a, A, b, B, and so on.
//NSEKEY-9598 and NSEKEY-9266 

=== Enhanced accrued burst display
The tooltip that appears when hovering over the capacity usage bar chart in the *Capacity Trend* tab now displays the type of accrued burst based on committed capacity. It differentiates between provisional and invoiced accrued burst, showing *Provisional Accrued Consumption* and *Invoiced Accrued Consumption* for subscriptions with zero committed capacity rate plans, and *Provisional Accrued Burst* and *Invoiced Accrued Burst* for those with non-zero committed capacity.
//NSEKEY-9750

== May 09, 2024

=== New columns in CSV reports 
The CSV reports from the *Capacity Trend* tab now include *Subscription Number* and *Account Name* columns for improved detail.
//NSEKEY-8889

=== Enhanced Usage Type column
The *Usage Type* column within the *Subscriptions* tab is enhanced to display logical and physical usages as comma-separated values for subscriptions that cover service levels for both file and object.
//NSEKEY-9540

=== Access object storage details from Volume Details tab
The *Volume Details* tab within the *Volumes & Objects* tab now provides object storage details along with volume information for subscriptions that include service levels for both file and object. You can click the *Object Storage Details* button within the *Volume Details* tab to view the details.

== March 28, 2024

=== Improvement to QoS policy compliance display in the Volume Details tab
The *Volume Details* tab within the *Volumes & Objects* tab now provides better visibility into Quality of Service (QoS) policy compliance. The column formerly known as *AQoS* is renamed to *Compliant*, which indicates whether the QoS policy is in compliance. In addition, a new column *QoS Policy Type* is added, which specifies if the policy is fixed or adaptive. If neither applies, the column displays _Not Available_. For more information, see link:../integrations/volumes-objects-tab.html[Volumes & Objects tab^].


=== New column and simplified subscription display in the Volume Summary tab
* The *Volume Summary* tab within the *Volumes & Objects* tab now includes a new column titled *Protected*. This column provides a count of the protected volumes associated with your subscribed service levels. If you click the number of protected volumes, it takes you to the *Volume Details* tab, where you can view a filtered list of protected volumes.
* The *Volume Summary* tab is updated to display only base subscriptions, excluding add-on services. For more information, see link:../integrations/volumes-objects-tab.html[Volumes & Objects tab^].


=== Change to accrued burst detail display in the Capacity Trend tab
The tooltip that appears when hovering over the capacity usage bar chart in the *Capacity Trend* tab will display the details of accrued bursts for the current month. The details will not be available for the previous months.

=== Enhanced access to view historical data for Keystone subscriptions
You can now view historical data if a Keystone subscription is modified or renewed. You can set the start date of a subscription to a previous date to view :

* Consumption and accrued burst usage data from the *Capacity Trend* tab,
* Performance metrics of ONTAP volumes from the *Performance* tab,

all of which show the data based on the selected date of the subscription.

== February 29, 2024

=== Addition of the Assets tab
The *Keystone Subscriptions* screen now includes the *Assets* tab. This new tab provides cluster-level information based on your subscriptions. For more information, see link:../integrations/assets-tab.html[Assets tab^].

=== Improvements to the Volumes & Objects tab 
To provide better clarity to your ONTAP system volumes, two new tab buttons, *Volume Summary* and *Volume Details*, have been added to the *Volumes* tab. The *Volume Summary* tab provides an overall count of the volumes associated with your subscribed service levels, including their AQoS compliance status and capacity information. The *Volume Details* tab lists all the volumes and their specifics. For more information, see link:../integrations/volumes-objects-tab.html[Volumes & Objects tab^].

=== Enhanced search experience on Digital Advisor
The search parameters on the *Digital Advisor* screen now include Keystone subscription numbers and watchlists created for Keystone subscriptions. You can enter the first three characters of a subscription number or watchlist name. For more information, see link:../integrations/keystone-aiq.html[View Keystone dashboard on Active IQ Digital Advisor^].

=== View timestamp of the consumption data 
You can view the timestamp of the consumption data (in UTC) on the old dashboard of the *Keystone Subscriptions* widget. 


== February 13, 2024

=== Ability to view subscriptions linked to a primary subscription
Some of your primary subscriptions can have linked, secondary subscriptions. If that is the case, the primary subscription number will continue to be displayed in the *Subscription Number* column, while the linked subscription numbers will be listed in a new column *Linked Subscriptions* on the *Subscriptions* tab. The *Linked Subscriptions* column becomes available to you only if you have linked subscriptions, and you can see information messages notifying you about them.

== January 11, 2024

=== Invoiced data returned for accrued burst
The labels for *Accrued Burst* are now modified to *Invoiced Accrued Burst* in the *Capacity Trend* tab. Selecting this option enables you to view the the monthly charts for the billed accrued burst data. For more information, see link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst[View invoiced accrued burst^].

=== Accrued consumption details for specific rate plans
If you have a subscription that has rate plans with _zero_ committed capacity, you can view the accrued consumption details in the *Capacity Trend* tab. On selecting the *Invoiced Accrued Consumption* option, you can view the the monthly charts for the billed accrued consumption data.


== December 15, 2023

=== Ability to search by watchlists
The support for watchlists in Digital Advisor has been extended to include Keystone systems. You can now view the details of the subscriptions for multiple customers by searching with watchlists. For more information about the use of watchlists in Keystone STaaS, see link:../integrations/keystone-aiq.html#search-by-keystone-watchlists[Search by Keystone watchlists^].

=== Date converted to UTC timezone
The data returned on the tabs of the *Keystone Subscriptions* screen of Digital Advisor is displayed in UTC time (server timezone). When you enter a date for query, it is automatically considered to be in UTC time. For more information, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting^].


// NSEKEY-8001, NSEKEY-8884, NSEKEY-8042, NSEKEY-8877, NSEKEY-8885, NSEKEY-8887, NSEKEY-8043, Clear filter button: Feb 2024.



