---
sidebar: sidebar
permalink: release-notes/whats-new.html
keywords: new features, release notes, enhancements, what's new
summary: Keystone STaaS new features and enhancements.
---

= What's new in Keystone STaaS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp offers you new and enhanced features in every release of Keystone STaaS services.

== New features and enhancements for January 31, 2024
The following change has been made on the *Keystone Subscriptions* screen of Active IQ Digital Advisor (also known as Digital Advisor).

=== Ability to view subscriptions linked to a primary subscription
If secondary subscriptions are linked to a primary subscription, you can see the linked subscription numbers listed against the primary subscription in the *Linked Subscriptions* column of the *Subscriptions* tab. This column is available to you only if you have any subscription linked to your primary subscription, which is displayed in the *Subscription Number* column. In case there are linked subscriptions, an information message is displayed informing  you of the subscriptions.


== New features and enhancements for January 11, 2024

Learn what's new in this release.

The following changes have been made on the *Keystone Subscriptions* screen of Active IQ Digital Advisor (also known as Digital Advisor).

=== Invoiced data returned for accrued burst
The labels for *Accrued Burst* are now modified to *Invoiced Accrued Burst* in the *Capacity Trend* tab. Selecting this option enables you to view the the monthly charts for the billed accrued burst data. For more information, see link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst[View invoiced accrued burst^].

=== Accrued consumption details for specific rate plans
If you have a subscription that has rate plans with _zero_ committed capacity, you can view the accrued consumption details in the *Capacity Trend* tab. On selecting the *Invoiced Accrued Consumption* option, you can view the the monthly charts for the billed accrued consumption data.


== New features and enhancements for December 15, 2023

Learn what's new in this release.

=== Ability to search by watchlists
The support for watchlists in Active IQ Digital Advisor (also known as Digital Advisor) has been extended to include Keystone systems. You can now view the details of the subscriptions for multiple customers by searching with watchlists. For more information about the use of watchlists in Keystone STaaS, see link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists[Search by using Keystone watchlists^].

=== Date converted to UTC timezone
The data returned on the tabs of the *Keystone Subscriptions* screen of Active IQ Digital Advisor is displayed in UTC time (server timezone). When you enter a date for query, it is automatically considered to be in UTC time. For more information, see link:../integrations/aiq-keystone-details.html[Keystone Subscription dashboard and reporting^].





